ordering items took 0:00:01
Tests considered 72 and ignored 317
2023-12-31 00:53:25,755 T0000: NOTICE WORKER = gw1
2023-12-31 00:53:25,755 T0000: NOTICE using testbed file /data/work/logs/docker-master-444338-l3/testbed_1_4_1.yaml
2023-12-31 00:53:25,755 T0000: NOTICE Execution Start Time: 2023-12-31 00:53:25.754054
2023-12-31 00:53:25,755 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-444338-l3/gw1
2023-12-31 00:53:26,278 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-31 00:53:26,278 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 42.8%
2023-12-31 00:53:26,278 T0000: NOTICE ROOT_PATH: /repo
2023-12-31 00:53:26,278 T0000: NOTICE Python: 3.8.10
2023-12-31 00:53:26,278 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D1D3:4,D1D4:4,D2T1:4,D2D3:4,D2D4:4,D3T1:4,D3D4:6,D4T1:4
2023-12-31 00:53:26,278 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-31 00:53:26,278 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-31-00-53-15 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-444338-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-444338-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-444338-l3 --noop --feature-group master
2023-12-31 00:53:26,900 T0000: DEBUG 'errors' not set in properties for V1 assuming 'default'
2023-12-31 00:53:26,901 T0000: DEBUG 'errors' not set in properties for V2 assuming 'default'
2023-12-31 00:53:26,901 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2023-12-31 00:53:26,901 T0000: DEBUG 'errors' not set in properties for V4 assuming 'default'
2023-12-31 00:53:26,901 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-31 00:53:26,901 T0000: WARN  Registering Topology
2023-12-31 00:53:26,925 T0000: INFO  Connecting all devices
2023-12-31 00:53:26,927 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8', '1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'] skip: False
2023-12-31 00:53:27,943 T0012: INFO  [D1-V1] Connecting to device (V1): sonic_ssh: 172.18.0.2:22 ..
2023-12-31 00:53:27,943 T0012: INFO  [D1-V1] TRY Authentication: 172.18.0.2:22 admin YourPaSsWoRd
2023-12-31 00:53:27,950 T0013: INFO  [D2-V2] Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2023-12-31 00:53:27,950 T0013: INFO  [D2-V2] TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2023-12-31 00:53:27,957 T0014: INFO  [D3-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2023-12-31 00:53:27,958 T0014: INFO  [D3-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2023-12-31 00:53:27,964 T0015: INFO  [D4-V4] Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2023-12-31 00:53:27,965 T0015: INFO  [D4-V4] TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2023-12-31 00:53:27,970 T0000: INFO  TG Scapy Init
2023-12-31 00:53:27,971 T0000: INFO  TG Base Init skip: False
2023-12-31 00:53:27,981 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-31 00:53:28,077 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_31_00_53_28_009083/gw1/default.log
2023-12-31 00:53:28,085 T0000: DEBUG REQ: tg_connect(port_list=['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8', '1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'])
2023-12-31 00:53:33,176 T0013: DEBUG [D2-V2] Connected ...
2023-12-31 00:53:33,180 T0014: DEBUG [D3-V3] Connected ...
2023-12-31 00:53:33,184 T0012: DEBUG [D1-V1] Connected ...
2023-12-31 00:53:33,188 T0015: DEBUG [D4-V4] Connected ...
2023-12-31 00:53:34,019 T0014: INFO  [D3-V3] Prompt at the connection start: 'admin@V3:~$' 
2023-12-31 00:53:34,023 T0014: AUDIT [D3-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-31 00:53:34,026 T0015: INFO  [D4-V4] Prompt at the connection start: 'admin@V4:~$' 
2023-12-31 00:53:34,027 T0015: AUDIT [D4-V4] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-31 00:53:34,033 T0013: INFO  [D2-V2] Prompt at the connection start: 'admin@V2:~$' 
2023-12-31 00:53:34,034 T0013: AUDIT [D2-V2] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-31 00:53:34,038 T0012: INFO  [D1-V1] Prompt at the connection start: 'admin@V1:~$' 
2023-12-31 00:53:34,039 T0012: AUDIT [D1-V1] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-31 00:53:34,435 T0014: INFO  [D3-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-31 00:53:34,442 T0015: INFO  [D4-V4] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-31 00:53:34,448 T0013: INFO  [D2-V2] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-31 00:53:34,453 T0012: INFO  [D1-V1] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-31 00:53:34,695 T0014: INFO  [D3-V3]  00:53:34 up 23 days,  1:56,  1 user,  load average: 104.79, 42.32, 20.27
2023-12-31 00:53:34,696 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:53:34,702 T0014: AUDIT [D3-V3] cat /proc/uptime
2023-12-31 00:53:34,706 T0015: INFO  [D4-V4]  00:53:34 up 23 days,  1:56,  1 user,  load average: 104.79, 42.32, 20.27
2023-12-31 00:53:34,706 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:53:34,708 T0015: AUDIT [D4-V4] cat /proc/uptime
2023-12-31 00:53:34,710 T0013: INFO  [D2-V2]  00:53:34 up 23 days,  1:56,  1 user,  load average: 104.79, 42.32, 20.27
2023-12-31 00:53:34,710 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:53:34,711 T0013: AUDIT [D2-V2] cat /proc/uptime
2023-12-31 00:53:34,715 T0012: INFO  [D1-V1]  00:53:34 up 23 days,  1:56,  1 user,  load average: 104.79, 42.32, 20.27
2023-12-31 00:53:34,715 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:53:34,717 T0012: AUDIT [D1-V1] cat /proc/uptime
2023-12-31 00:53:35,109 T0014: INFO  [D3-V3] FCMD: cat /proc/uptime
2023-12-31 00:53:35,118 T0015: INFO  [D4-V4] FCMD: cat /proc/uptime
2023-12-31 00:53:35,123 T0013: INFO  [D2-V2] FCMD: cat /proc/uptime
2023-12-31 00:53:35,128 T0012: INFO  [D1-V1] FCMD: cat /proc/uptime
2023-12-31 00:53:35,365 T0014: INFO  [D3-V3] 1994213.63 157225969.54
2023-12-31 00:53:35,365 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:53:35,366 T0014: INFO  [D3-V3] UPTIME: 1994213.63
2023-12-31 00:53:35,367 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:35,378 T0015: INFO  [D4-V4] 1994213.64 157225969.91
2023-12-31 00:53:35,379 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:53:35,381 T0015: INFO  [D4-V4] UPTIME: 1994213.64
2023-12-31 00:53:35,381 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:35,386 T0013: INFO  [D2-V2] 1994213.64 157225970.20
2023-12-31 00:53:35,386 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:53:35,390 T0012: INFO  [D1-V1] 1994213.64 157225970.28
2023-12-31 00:53:35,390 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:53:35,392 T0013: INFO  [D2-V2] UPTIME: 1994213.64
2023-12-31 00:53:35,393 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:35,395 T0012: INFO  [D1-V1] UPTIME: 1994213.64
2023-12-31 00:53:35,395 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:35,775 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:35,794 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:35,803 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:35,809 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:36,384 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:53:36,385 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:53:36,387 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:36,389 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:36,390 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:36,404 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:53:36,405 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:53:36,407 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:36,409 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:36,409 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:36,418 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:53:36,418 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:53:36,421 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:53:36,422 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:53:36,425 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:36,427 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:36,429 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:36,429 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:36,430 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:36,430 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:41,395 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:41,415 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:41,434 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:41,435 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:41,802 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:41,822 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:41,848 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:41,854 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:42,414 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:53:42,415 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:53:42,417 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:42,419 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:42,419 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:42,433 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:53:42,433 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:53:42,435 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:42,436 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:42,437 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:42,514 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:53:42,514 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:53:42,516 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:53:42,517 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:53:42,519 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:42,521 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:42,523 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:42,523 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:42,525 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:42,525 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:47,425 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:47,442 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:47,529 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:47,531 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:47,833 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:47,850 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:47,943 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:47,949 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:48,216 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/1": "port-1", "1/2": "port-2", "1/3": "port-3", "1/4": "port-4", "1/5": "port-5", "1/6": "port-6", "1/7": "port-7", "1/8": "port-8", "1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12", "1/13": "port-13", "1/14": "port-14", "1/15": "port-15", "1/16": "port-16"}, "status": 1}
2023-12-31 00:53:48,243 T0000: INFO  TG Connection: Success
2023-12-31 00:53:48,243 T0000: INFO  TG Connect...done
2023-12-31 00:53:48,448 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:53:48,448 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:53:48,451 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:48,453 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:48,453 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:48,461 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:53:48,461 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:53:48,464 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:48,466 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:48,466 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:48,559 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:53:48,560 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:53:48,562 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:53:48,562 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:53:48,565 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:48,568 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:48,569 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:48,569 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:48,570 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:48,571 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:53,459 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:53,471 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:53,572 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:53,576 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:53,866 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:53,879 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:53,978 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:53,985 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:54,477 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:53:54,477 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:53:54,480 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:54,482 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:54,482 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:54,490 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:53:54,491 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:53:54,494 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:54,497 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:54,497 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:54,588 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:53:54,588 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:53:54,591 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:54,593 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:54,593 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:54,595 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:53:54,596 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:53:54,598 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:54,600 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:53:54,600 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:53:59,486 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:59,503 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:59,595 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:59,603 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:59,892 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:53:59,910 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:00,002 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:00,010 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:00,551 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:00,551 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:00,554 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:00,555 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:00,555 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:00,572 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:00,572 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:00,575 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:00,577 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:00,577 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:00,613 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:00,613 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:00,615 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:00,617 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:00,618 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:00,619 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:00,620 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:00,621 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:00,622 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:00,622 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:05,561 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:05,582 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:05,623 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:05,627 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:05,968 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:05,990 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:06,034 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:06,040 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:06,579 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:06,579 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:06,581 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:06,583 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:06,583 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:06,600 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:06,600 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:06,602 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:06,604 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:06,604 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:06,650 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:06,650 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:06,653 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:06,653 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:06,656 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:06,658 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:06,660 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:06,660 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:06,661 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:06,661 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:11,589 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:11,609 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:11,666 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:11,667 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:11,999 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,017 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,079 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,085 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,627 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:12,628 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:12,630 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,632 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:12,632 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:12,660 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:12,660 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:12,662 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,664 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:12,665 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:12,697 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:12,697 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:12,700 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:12,700 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:12,703 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,705 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:12,707 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:12,707 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:12,709 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:12,709 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:17,635 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:17,670 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:17,712 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:17,712 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,042 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,078 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,126 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,132 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,703 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:18,703 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:18,706 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,708 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:18,708 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:18,737 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:18,737 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:18,740 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,743 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:18,743 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:18,745 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:18,746 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:18,747 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,749 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:18,749 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:18,790 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:18,790 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:18,792 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:18,794 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:18,794 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:23,712 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:23,752 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:23,752 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:23,800 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,119 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,164 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,171 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,207 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,729 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:24,730 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:24,732 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,735 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:24,735 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:24,776 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:24,776 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:24,778 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,778 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:24,778 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:24,783 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:24,783 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:24,786 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,788 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:24,788 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:24,816 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:24,816 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:24,818 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:24,820 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:24,820 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:29,740 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:29,784 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:29,791 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:29,826 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,147 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,193 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,198 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,232 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,758 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:30,758 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:30,761 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,763 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:30,763 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:30,803 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:30,803 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:30,806 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,808 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:30,808 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:30,810 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:30,810 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:30,812 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,814 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:30,814 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:30,843 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:30,843 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:30,845 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:30,847 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:30,847 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:35,767 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:35,814 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:35,820 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:35,853 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,174 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,221 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,226 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,260 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,785 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:36,785 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:36,788 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,790 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:36,790 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:36,831 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:36,832 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:36,834 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,837 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:36,837 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:36,840 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:36,840 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:36,842 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,844 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:36,844 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:36,920 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:36,920 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:36,923 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:36,925 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:36,925 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:41,796 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:41,843 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:41,847 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:41,930 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,203 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,250 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,256 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,337 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,816 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:42,816 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:42,819 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,821 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:42,821 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:42,864 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:42,864 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:42,866 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,868 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:42,869 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:42,917 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:42,917 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:42,919 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,921 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:42,921 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:42,948 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:42,948 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:42,950 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:42,952 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:42,952 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:47,827 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:47,874 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:47,927 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:47,957 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,235 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,281 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,336 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,364 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,849 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:48,850 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:48,853 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,856 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:48,856 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:48,891 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:48,891 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:48,896 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,897 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:48,898 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:48,947 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:48,947 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:48,950 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,952 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:48,952 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:48,974 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:48,975 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:48,977 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:48,979 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:48,979 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:53,860 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:53,903 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:53,958 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:53,985 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,267 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,310 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,365 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,391 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,876 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:54:54,876 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:54:54,878 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,879 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:54,879 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:54,921 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:54:54,921 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:54:54,924 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,925 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:54,925 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:54,975 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:54:54,976 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:54:54,978 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:54,980 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:54,980 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:55,001 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:54:55,002 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:54:55,004 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:55,006 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:54:55,006 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:54:59,883 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:59,927 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:54:59,986 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,011 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,291 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,334 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,396 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,418 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,901 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:55:00,902 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:00,904 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,909 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:00,909 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:00,944 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:55:00,944 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:00,946 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:00,948 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:00,948 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:01,009 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:55:01,009 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:01,012 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:01,014 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:01,014 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:01,027 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:55:01,027 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:01,030 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:01,032 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:01,032 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:05,915 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:05,951 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,020 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,038 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,322 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,358 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,431 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,445 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,932 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:55:06,932 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:06,935 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,936 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:06,936 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:06,968 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:55:06,968 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:06,970 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:06,972 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:06,972 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:07,040 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:55:07,040 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:07,043 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:07,044 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:07,044 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:07,055 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:55:07,055 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:07,058 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:07,059 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:07,060 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:11,940 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:11,975 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,050 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,065 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,347 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,383 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,457 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,471 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,958 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:55:12,958 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:12,960 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,962 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:12,962 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:12,993 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:55:12,993 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:12,995 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:12,996 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:12,996 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:13,066 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:55:13,066 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:13,068 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:13,069 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:13,069 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:13,130 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:55:13,130 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:13,131 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:13,133 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:13,133 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:17,968 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,002 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,075 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,138 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,375 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,409 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,484 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,545 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,987 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:55:18,987 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:18,990 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:18,992 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:18,992 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:19,019 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:55:19,019 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:19,022 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:19,024 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:19,024 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:19,098 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:55:19,099 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:19,101 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:19,103 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:19,103 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:19,155 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:55:19,156 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:19,158 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:19,160 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:19,160 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:23,998 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:24,027 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:24,109 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:24,163 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:24,405 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:24,434 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:24,517 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:24,570 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:25,015 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:55:25,015 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:25,018 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:25,020 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:25,020 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:25,044 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:55:25,044 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:25,047 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:25,049 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:25,049 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:25,180 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:55:25,180 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:25,183 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:25,185 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:25,185 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:25,228 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:55:25,228 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:25,231 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:25,233 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:25,233 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:30,023 T0015: AUDIT [D4-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:30,055 T0014: AUDIT [D3-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:30,191 T0012: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:30,239 T0013: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:30,431 T0015: INFO  [D4-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:30,462 T0014: INFO  [D3-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:30,598 T0012: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:30,646 T0013: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:31,042 T0015: INFO  [D4-V4] Error response from daemon: No such container: bgp
2023-12-31 00:55:31,042 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:31,044 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:31,046 T0015: WARN  [D4-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:31,046 T0015: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:31,123 T0014: INFO  [D3-V3] Error response from daemon: No such container: bgp
2023-12-31 00:55:31,123 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:31,125 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:31,127 T0014: WARN  [D3-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:31,128 T0014: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:31,207 T0012: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:55:31,207 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:31,209 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:31,211 T0012: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:31,211 T0012: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:31,256 T0013: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 00:55:31,257 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:31,259 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:55:31,261 T0013: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:55:31,261 T0013: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:55:36,053 T0015: ERROR [D4-V4] Failed to read hostname from vtysh - assuming sonic
2023-12-31 00:55:36,056 T0015: INFO  [D4-V4] Base Prompt: sonic
2023-12-31 00:55:36,057 T0015: DEBUG [D4-V4] Wait for system ready Ref: 866
2023-12-31 00:55:36,132 T0014: ERROR [D3-V3] Failed to read hostname from vtysh - assuming sonic
2023-12-31 00:55:36,134 T0014: INFO  [D3-V3] Base Prompt: sonic
2023-12-31 00:55:36,136 T0014: DEBUG [D3-V3] Wait for system ready Ref: 866
2023-12-31 00:55:36,218 T0012: ERROR [D1-V1] Failed to read hostname from vtysh - assuming sonic
2023-12-31 00:55:36,220 T0012: INFO  [D1-V1] Base Prompt: sonic
2023-12-31 00:55:36,221 T0012: DEBUG [D1-V1] Wait for system ready Ref: 866
2023-12-31 00:55:36,266 T0013: ERROR [D2-V2] Failed to read hostname from vtysh - assuming sonic
2023-12-31 00:55:36,268 T0013: INFO  [D2-V2] Base Prompt: sonic
2023-12-31 00:55:36,269 T0013: DEBUG [D2-V2] Wait for system ready Ref: 866
2023-12-31 00:55:36,464 T0015: INFO  [D4-V4] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:36,543 T0014: INFO  [D3-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:36,627 T0012: INFO  [D1-V1] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:36,674 T0013: INFO  [D2-V2] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:36,771 T0015: INFO  [D4-V4] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-31 00:55:36,771 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:36,775 T0015: INFO  [D4-V4] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-31 00:55:36,778 T0015: INFO  [D4-V4] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:36,780 T0015: INFO  [D4-V4] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V4): /tmp/spytest-helper.py
2023-12-31 00:55:36,783 T0015: ERROR [D4-V4] No mgmt IP
2023-12-31 00:55:36,783 T0015: INFO  [D4-V4] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-31 00:55:36,802 T0014: INFO  [D3-V3] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-31 00:55:36,803 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:36,807 T0014: INFO  [D3-V3] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-31 00:55:36,807 T0014: INFO  [D3-V3] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:36,808 T0014: INFO  [D3-V3] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V3): /tmp/spytest-helper.py
2023-12-31 00:55:36,809 T0014: ERROR [D3-V3] No mgmt IP
2023-12-31 00:55:36,810 T0014: INFO  [D3-V3] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-31 00:55:36,884 T0012: INFO  [D1-V1] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-31 00:55:36,884 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:36,888 T0012: INFO  [D1-V1] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-31 00:55:36,889 T0012: INFO  [D1-V1] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:36,890 T0012: INFO  [D1-V1] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V1): /tmp/spytest-helper.py
2023-12-31 00:55:36,892 T0012: ERROR [D1-V1] No mgmt IP
2023-12-31 00:55:36,895 T0012: INFO  [D1-V1] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-31 00:55:36,930 T0013: INFO  [D2-V2] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-31 00:55:36,931 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:36,938 T0013: INFO  [D2-V2] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-31 00:55:36,939 T0013: INFO  [D2-V2] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:36,939 T0013: INFO  [D2-V2] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V2): /tmp/spytest-helper.py
2023-12-31 00:55:36,940 T0013: ERROR [D2-V2] No mgmt IP
2023-12-31 00:55:36,940 T0013: INFO  [D2-V2] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-31 00:55:36,970 T0015: INFO  [D4-V4] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-31 00:55:36,988 T0014: INFO  [D3-V3] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-31 00:55:37,066 T0012: INFO  [D1-V1] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-31 00:55:37,110 T0013: INFO  [D2-V2] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-31 00:55:37,228 T0015: INFO  [D4-V4] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-31 00:55:37,228 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:37,232 T0015: INFO  [D4-V4] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:37,233 T0015: INFO  [D4-V4] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:37,246 T0014: INFO  [D3-V3] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-31 00:55:37,247 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:37,252 T0014: INFO  [D3-V3] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:37,253 T0014: INFO  [D3-V3] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:37,323 T0012: INFO  [D1-V1] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-31 00:55:37,323 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:37,326 T0012: INFO  [D1-V1] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:37,328 T0012: INFO  [D1-V1] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:37,367 T0013: INFO  [D2-V2] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-31 00:55:37,367 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:37,370 T0013: INFO  [D2-V2] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 00:55:37,372 T0013: INFO  [D2-V2] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-31 00:55:39,842 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:39,844 T0015: WARN  [D4-V4] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-31 00:55:39,846 T0015: INFO  [D4-V4] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:39,859 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:39,862 T0014: WARN  [D3-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-31 00:55:39,863 T0014: INFO  [D3-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:39,936 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:39,938 T0012: WARN  [D1-V1] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-31 00:55:39,939 T0012: INFO  [D1-V1] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:39,980 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:39,982 T0013: WARN  [D2-V2] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-31 00:55:39,984 T0013: INFO  [D2-V2] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,688 T0015: WARN  [D4-V4] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,690 T0014: WARN  [D3-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,691 T0015: INFO  [D4-V4] 
2023-12-31 00:55:43,691 T0015: INFO  [D4-V4] Remote CMD: 'show platform summary'
2023-12-31 00:55:43,691 T0015: INFO  [D4-V4] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,691 T0015: INFO  [D4-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,691 T0015: INFO  [D4-V4]     from show.main import cli
2023-12-31 00:55:43,691 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,691 T0015: INFO  [D4-V4]     if is_gearbox_configured():
2023-12-31 00:55:43,692 T0015: INFO  [D4-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,692 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,692 T0015: INFO  [D4-V4]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,692 T0015: INFO  [D4-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,692 T0015: INFO  [D4-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,692 T0015: INFO  [D4-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,692 T0015: INFO  [D4-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,693 T0015: INFO  [D4-V4] 
2023-12-31 00:55:43,693 T0015: INFO  [D4-V4] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-31 00:55:43,693 T0015: INFO  [D4-V4] Remote CMD: 'sudo show interfaces status '
2023-12-31 00:55:43,693 T0015: INFO  [D4-V4] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,693 T0015: INFO  [D4-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,693 T0015: INFO  [D4-V4]     from show.main import cli
2023-12-31 00:55:43,693 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,694 T0015: INFO  [D4-V4]     if is_gearbox_configured():
2023-12-31 00:55:43,694 T0015: INFO  [D4-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,694 T0015: INFO  [D4-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,694 T0015: INFO  [D4-V4]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,694 T0015: INFO  [D4-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,694 T0015: INFO  [D4-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,695 T0015: INFO  [D4-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,695 T0015: INFO  [D4-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,695 T0015: INFO  [D4-V4] 
2023-12-31 00:55:43,695 T0015: INFO  [D4-V4] admin@V4:~$ 
2023-12-31 00:55:43,702 T0014: INFO  [D3-V3] 
2023-12-31 00:55:43,702 T0014: INFO  [D3-V3] Remote CMD: 'show platform summary'
2023-12-31 00:55:43,702 T0014: INFO  [D3-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,702 T0014: INFO  [D3-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,702 T0014: INFO  [D3-V3]     from show.main import cli
2023-12-31 00:55:43,702 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,702 T0014: INFO  [D3-V3]     if is_gearbox_configured():
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,703 T0014: INFO  [D3-V3] 
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3] Remote CMD: 'sudo show interfaces status '
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3]     from show.main import cli
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3]     if is_gearbox_configured():
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,704 T0014: INFO  [D3-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,705 T0014: INFO  [D3-V3]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,705 T0014: INFO  [D3-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,705 T0014: INFO  [D3-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,705 T0014: INFO  [D3-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,705 T0014: INFO  [D3-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,705 T0014: INFO  [D3-V3] 
2023-12-31 00:55:43,705 T0014: INFO  [D3-V3] admin@V3:~$ 
2023-12-31 00:55:43,706 T0014: ERROR [D3-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,707 T0015: ERROR [D4-V4] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,763 T0012: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,763 T0012: INFO  [D1-V1] 
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1] Remote CMD: 'show platform summary'
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1]     from show.main import cli
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,764 T0012: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1] 
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1] Remote CMD: 'sudo show interfaces status '
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,765 T0012: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]     from show.main import cli
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,766 T0012: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,767 T0012: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,767 T0012: INFO  [D1-V1] 
2023-12-31 00:55:43,767 T0012: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:55:43,767 T0012: ERROR [D1-V1] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,810 T0013: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,810 T0013: INFO  [D2-V2] 
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2] Remote CMD: 'show platform summary'
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2]     from show.main import cli
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2]     if is_gearbox_configured():
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,811 T0013: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2] 
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2] Remote CMD: 'sudo show interfaces status '
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 00:55:43,812 T0013: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]     from show.main import cli
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]     if is_gearbox_configured():
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 00:55:43,813 T0013: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 00:55:43,814 T0013: INFO  [D2-V2] 
2023-12-31 00:55:43,814 T0013: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 00:55:43,814 T0013: ERROR [D2-V2] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 00:55:43,815 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-31 00:55:43,815 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-31 00:55:43,815 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-31 00:55:43,816 T0011: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-31 00:55:43,817 T0011: ERROR [D1-V1] Failed to connect to device
2023-12-31 00:55:43,818 T0011: ERROR [D2-V2] Failed to connect to device
2023-12-31 00:55:43,819 T0011: ERROR [D3-V3] Failed to connect to device
2023-12-31 00:55:43,820 T0011: ERROR [D4-V4] Failed to connect to device
2023-12-31 00:55:43,820 T0000: ERROR Failed to connect (['V1', 'V2', 'V3', 'V4'])
2023-12-31 00:55:43,821 T0000: INFO  --FINISH--RUN--4 @559
