ordering items took 0:00:01
Tests considered 69 and ignored 320
2023-12-28 01:55:00,536 T0000: NOTICE WORKER = gw2
2023-12-28 01:55:00,536 T0000: NOTICE using testbed file /data/work/logs/docker-master-442372-l2/testbed_1_2_1.yaml
2023-12-28 01:55:00,536 T0000: NOTICE Execution Start Time: 2023-12-28 01:55:00.535177
2023-12-28 01:55:00,536 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-442372-l2/gw2
2023-12-28 01:55:01,054 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-28 01:55:01,054 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 38.6%
2023-12-28 01:55:01,054 T0000: NOTICE ROOT_PATH: /repo
2023-12-28 01:55:01,054 T0000: NOTICE Python: 3.8.10
2023-12-28 01:55:01,054 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D2T1:4
2023-12-28 01:55:01,054 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-28 01:55:01,054 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-28-01-54-50 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-442372-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-442372-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-442372-l2 --noop --feature-group master
2023-12-28 01:55:01,692 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2023-12-28 01:55:01,692 T0000: DEBUG 'errors' not set in properties for V4 assuming 'default'
2023-12-28 01:55:01,693 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-28 01:55:01,693 T0000: WARN  Registering Topology
2023-12-28 01:55:01,713 T0000: INFO  Connecting all devices
2023-12-28 01:55:01,714 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'] skip: False
2023-12-28 01:55:02,241 T0005: INFO  [D1-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2023-12-28 01:55:02,241 T0005: INFO  [D1-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2023-12-28 01:55:02,248 T0006: INFO  [D2-V4] Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2023-12-28 01:55:02,248 T0006: INFO  [D2-V4] TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2023-12-28 01:55:02,735 T0000: INFO  TG Scapy Init
2023-12-28 01:55:02,735 T0000: INFO  TG Base Init skip: False
2023-12-28 01:55:02,746 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-28 01:55:02,859 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_28_01_55_02_775773/gw2/default.log
2023-12-28 01:55:02,868 T0000: DEBUG REQ: tg_connect(port_list=['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'])
2023-12-28 01:55:07,475 T0006: DEBUG [D2-V4] Connected ...
2023-12-28 01:55:07,481 T0005: DEBUG [D1-V3] Connected ...
2023-12-28 01:55:08,306 T0005: INFO  [D1-V3] Prompt at the connection start: 'admin@V3:~$' 
2023-12-28 01:55:08,308 T0005: AUDIT [D1-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-28 01:55:08,311 T0006: INFO  [D2-V4] Prompt at the connection start: 'admin@V4:~$' 
2023-12-28 01:55:08,312 T0006: AUDIT [D2-V4] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-28 01:55:08,721 T0006: INFO  [D2-V4] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-28 01:55:08,727 T0005: INFO  [D1-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-28 01:55:08,983 T0006: INFO  [D2-V4]  01:55:08 up 20 days,  2:57,  1 user,  load average: 93.84, 31.72, 14.41
2023-12-28 01:55:08,983 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:08,994 T0006: AUDIT [D2-V4] cat /proc/uptime
2023-12-28 01:55:08,997 T0005: INFO  [D1-V3]  01:55:08 up 20 days,  2:57,  1 user,  load average: 93.84, 31.72, 14.41
2023-12-28 01:55:08,997 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:08,999 T0005: AUDIT [D1-V3] cat /proc/uptime
2023-12-28 01:55:09,399 T0006: INFO  [D2-V4] FCMD: cat /proc/uptime
2023-12-28 01:55:09,405 T0005: INFO  [D1-V3] FCMD: cat /proc/uptime
2023-12-28 01:55:09,655 T0006: INFO  [D2-V4] 1738652.41 137100368.13
2023-12-28 01:55:09,656 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:09,658 T0006: INFO  [D2-V4] UPTIME: 1738652.41
2023-12-28 01:55:09,658 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:09,664 T0005: INFO  [D1-V3] 1738652.41 137100368.13
2023-12-28 01:55:09,664 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:09,666 T0005: INFO  [D1-V3] UPTIME: 1738652.41
2023-12-28 01:55:09,666 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:10,067 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:10,073 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:10,678 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:10,678 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:10,681 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:10,684 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:10,684 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:10,686 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:10,686 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:10,687 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:10,688 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:10,688 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:13,337 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12", "1/13": "port-13", "1/14": "port-14", "1/15": "port-15", "1/16": "port-16"}, "status": 1}
2023-12-28 01:55:13,350 T0000: INFO  TG Connection: Success
2023-12-28 01:55:13,350 T0000: INFO  TG Connect...done
2023-12-28 01:55:15,690 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:15,693 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:16,098 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:16,104 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:16,712 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:16,712 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:16,715 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:16,717 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:16,717 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:16,764 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:16,764 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:16,767 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:16,769 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:16,769 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:21,723 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:21,774 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:22,130 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:22,184 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:22,791 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:22,791 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:22,794 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:22,796 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:22,796 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:22,844 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:22,845 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:22,849 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:22,850 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:22,850 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:27,798 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:27,855 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:28,205 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:28,262 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:28,815 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:28,815 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:28,818 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:28,820 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:28,820 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:28,871 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:28,871 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:28,873 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:28,875 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:28,875 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:33,826 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:33,881 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:34,232 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:34,288 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:34,843 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:34,843 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:34,845 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:34,847 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:34,847 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:34,898 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:34,898 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:34,901 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:34,903 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:34,903 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:39,850 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:39,908 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:40,256 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:40,315 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:40,866 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:40,867 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:40,869 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:40,871 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:40,871 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:40,925 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:40,926 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:40,928 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:40,930 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:40,930 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:45,877 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:45,933 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:46,284 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:46,340 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:46,895 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:46,896 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:46,898 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:46,900 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:46,900 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:46,950 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:46,950 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:46,953 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:46,954 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:46,954 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:51,906 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:51,958 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:52,313 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:52,365 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:52,923 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:52,924 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:52,926 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:52,928 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:52,928 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:52,976 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:52,976 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:52,981 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:52,983 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:52,983 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:57,934 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:57,989 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:58,341 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:58,395 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:58,950 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:55:58,950 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:55:58,953 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:58,955 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:58,955 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:55:59,006 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:55:59,006 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:55:59,009 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:55:59,011 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:55:59,011 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:03,959 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:04,014 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:04,368 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:04,421 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:04,978 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:04,978 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:04,982 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:04,984 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:04,984 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:05,082 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:05,083 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:05,085 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:05,087 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:05,087 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:09,990 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:10,090 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:10,397 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:10,498 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:11,010 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:11,010 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:11,013 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:11,014 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:11,014 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:11,112 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:11,113 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:11,115 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:11,117 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:11,117 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:16,017 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:16,122 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:16,426 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:16,528 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:17,034 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:17,034 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:17,035 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:17,036 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:17,036 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:17,140 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:17,140 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:17,142 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:17,144 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:17,144 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:22,042 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:22,150 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:22,448 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:22,557 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:23,108 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:23,109 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:23,111 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:23,113 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:23,113 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:23,217 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:23,218 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:23,220 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:23,222 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:23,222 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:28,118 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:28,226 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:28,525 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:28,633 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:29,137 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:29,137 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:29,141 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:29,142 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:29,142 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:29,241 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:29,241 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:29,244 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:29,246 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:29,246 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:34,148 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:34,252 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:34,555 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:34,661 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:35,167 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:35,167 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:35,171 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:35,173 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:35,173 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:35,271 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:35,271 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:35,274 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:35,276 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:35,276 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:40,179 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:40,282 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:40,586 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:40,690 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:41,246 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:41,247 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:41,249 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:41,252 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:41,253 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:41,300 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:41,300 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:41,303 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:41,305 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:41,305 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:46,258 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:46,310 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:46,664 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:46,716 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:47,325 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:47,325 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:47,327 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:47,329 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:47,329 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:47,376 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:47,376 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:47,379 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:47,381 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:47,381 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:52,335 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:52,387 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:52,742 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:52,794 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:53,352 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:53,353 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:53,355 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:53,357 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:53,357 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:53,404 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:53,404 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:53,406 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:53,408 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:53,409 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:58,363 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:58,414 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:58,770 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:58,822 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:59,381 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:56:59,382 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:56:59,384 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:59,386 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:59,386 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:56:59,433 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:56:59,433 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:56:59,435 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:56:59,437 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:56:59,437 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:57:04,390 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:57:04,443 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:57:04,796 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:57:04,850 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:57:05,406 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-28 01:57:05,406 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:57:05,408 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:57:05,409 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:57:05,409 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:57:05,460 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-28 01:57:05,461 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:57:05,463 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:57:05,465 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:57:05,465 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:57:10,415 T0006: ERROR [D2-V4] Failed to read hostname from vtysh - assuming sonic
2023-12-28 01:57:10,417 T0006: INFO  [D2-V4] Base Prompt: sonic
2023-12-28 01:57:10,419 T0006: DEBUG [D2-V4] Wait for system ready Ref: 866
2023-12-28 01:57:10,472 T0005: ERROR [D1-V3] Failed to read hostname from vtysh - assuming sonic
2023-12-28 01:57:10,474 T0005: INFO  [D1-V3] Base Prompt: sonic
2023-12-28 01:57:10,475 T0005: DEBUG [D1-V3] Wait for system ready Ref: 866
2023-12-28 01:57:10,824 T0006: INFO  [D2-V4] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-28 01:57:10,881 T0005: INFO  [D1-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-28 01:57:11,081 T0006: INFO  [D2-V4] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-28 01:57:11,081 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:57:11,085 T0006: INFO  [D2-V4] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-28 01:57:11,087 T0006: INFO  [D2-V4] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-28 01:57:11,088 T0006: INFO  [D2-V4] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V4): /tmp/spytest-helper.py
2023-12-28 01:57:11,089 T0006: ERROR [D2-V4] No mgmt IP
2023-12-28 01:57:11,090 T0006: INFO  [D2-V4] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-28 01:57:11,137 T0005: INFO  [D1-V3] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-28 01:57:11,137 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:57:11,141 T0005: INFO  [D1-V3] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-28 01:57:11,142 T0005: INFO  [D1-V3] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-28 01:57:11,144 T0005: INFO  [D1-V3] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V3): /tmp/spytest-helper.py
2023-12-28 01:57:11,145 T0005: ERROR [D1-V3] No mgmt IP
2023-12-28 01:57:11,145 T0005: INFO  [D1-V3] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-28 01:57:11,256 T0006: INFO  [D2-V4] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-28 01:57:11,317 T0005: INFO  [D1-V3] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-28 01:57:11,512 T0006: INFO  [D2-V4] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-28 01:57:11,513 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:57:11,516 T0006: INFO  [D2-V4] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-28 01:57:11,518 T0006: INFO  [D2-V4] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-28 01:57:11,574 T0005: INFO  [D1-V3] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-28 01:57:11,574 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:57:11,578 T0005: INFO  [D1-V3] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-28 01:57:11,579 T0005: INFO  [D1-V3] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-28 01:57:14,126 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:57:14,128 T0006: WARN  [D2-V4] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-28 01:57:14,130 T0006: INFO  [D2-V4] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:57:14,187 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:57:14,189 T0005: WARN  [D1-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-28 01:57:14,191 T0005: INFO  [D1-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:57:17,956 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:57:17,958 T0006: INFO  [D2-V4] 
2023-12-28 01:57:17,959 T0006: INFO  [D2-V4] Remote CMD: 'show platform summary'
2023-12-28 01:57:17,959 T0006: INFO  [D2-V4] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-28 01:57:17,959 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-28 01:57:17,959 T0006: INFO  [D2-V4]     from show.main import cli
2023-12-28 01:57:17,960 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-28 01:57:17,960 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2023-12-28 01:57:17,960 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:17,960 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4] 
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4] Remote CMD: 'sudo show interfaces status '
2023-12-28 01:57:17,961 T0006: INFO  [D2-V4] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]     from show.main import cli
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4] 
2023-12-28 01:57:17,962 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-28 01:57:17,963 T0006: ERROR [D2-V4] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:57:18,012 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:57:18,012 T0005: INFO  [D1-V3] 
2023-12-28 01:57:18,012 T0005: INFO  [D1-V3] Remote CMD: 'show platform summary'
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3]     from show.main import cli
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-28 01:57:18,013 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3] 
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3] Remote CMD: 'sudo show interfaces status '
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-28 01:57:18,014 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]     from show.main import cli
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-28 01:57:18,015 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-28 01:57:18,016 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:57:18,016 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-28 01:57:18,016 T0005: INFO  [D1-V3] 
2023-12-28 01:57:18,016 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-28 01:57:18,017 T0005: ERROR [D1-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:57:18,017 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-28 01:57:18,017 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-28 01:57:18,019 T0004: ERROR [D1-V3] Failed to connect to device
2023-12-28 01:57:18,020 T0004: ERROR [D2-V4] Failed to connect to device
2023-12-28 01:57:18,020 T0000: ERROR Failed to connect (['V3', 'V4'])
2023-12-28 01:57:18,020 T0000: INFO  --FINISH--RUN--4 @559
