#,Node,Feature,TestCase,Result,ResultType,ExecutedOn,Description,Function,Module,Devices,KnownIssue
1,gw3,Regression,ft_add_unknownvlan_interface,Pass,Mapped,2023-12-30 02:57:48,Test case passed,test_ft_add_unknownvlan_interface,switching/test_vlan.py,"V3, V4",
2,gw3,Regression,ft_vlan_delete_with_member,Pass,Mapped,2023-12-30 02:58:00,Test case passed,test_ft_vlan_delete_with_member,switching/test_vlan.py,"V3, V4",
3,gw3,Regression,ft_vlan_trunk_tagged,Pass,Mapped,2023-12-30 02:59:26,Test case passed,test_ft_vlan_trunk_tagged,switching/test_vlan.py,"V3, V4",
4,gw3,Regression,ft_show_vlan_brief,Pass,Mapped,2023-12-30 02:59:26,Test case passed,test_ft_vlan_trunk_tagged,switching/test_vlan.py,"V3, V4",
5,gw2,Regression,FtOpSoSwLagFn042,Fail,Mapped,2023-12-30 02:59:42,"Portchannel PortChannel7 on V2 with member ['Ethernet16', 'Ethernet20'] verification failed",test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
6,gw2,Regression,FtOpSoSwLagFn041,Fail,Mapped,2023-12-30 02:59:42,"Portchannel PortChannel7 on V2 with member ['Ethernet16', 'Ethernet20'] verification failed",test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
7,gw2,PortChannel Config Enhancements,FtOpSoSwPominFn007,ConfigFail,Mapped,2023-12-30 03:00:21,pre-test configuration failed Invalid error code PortChannel Verification Failed : unknown message identifier 'PortChannel Verification Failed' @5430,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,switching/test_portchannel.py,"V1, V2",
8,gw3,warmboot,ft_reboot_fdb_fast_reboot,ScriptError,Mapped,2023-12-30 03:04:40,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
9,gw3,warmboot,ft_max_vlan_save_reload,ScriptError,Mapped,2023-12-30 03:04:40,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
10,gw3,warmboot,FtOpSoSysFRFn005,ScriptError,Mapped,2023-12-30 03:04:40,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
11,gw2,Regression,ft_lldp_LocManAddrLen,Fail,Mapped,2023-12-30 03:04:46,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrLen,system/test_lldp.py,"V1, V2",
12,gw2,Regression,ft_lldp_LocManAddrlfld,Fail,Mapped,2023-12-30 03:04:47,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrlfld,system/test_lldp.py,"V1, V2",
13,gw2,Regression,ft_lldp_LocManAddrEntry,Fail,Mapped,2023-12-30 03:04:47,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrEntry,system/test_lldp.py,"V1, V2",
14,gw2,Regression,ft_lldp_ConfigManAddrEntry,Fail,Mapped,2023-12-30 03:04:47,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_ConfigManAddrEntry,system/test_lldp.py,"V1, V2",
15,gw2,Regression,ft_lldp_lldplocportid,Fail,Mapped,2023-12-30 03:04:48,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocportid,system/test_lldp.py,"V1, V2",
16,gw2,Regression,ft_lldp_lldplocsysname,Fail,Mapped,2023-12-30 03:04:48,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysname,system/test_lldp.py,"V1, V2",
17,gw2,Regression,ft_lldp_lldplocsysdesc,Fail,Mapped,2023-12-30 03:04:49,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysdesc,system/test_lldp.py,"V1, V2",
18,gw2,SNMP Agent Optimization,ft_snmp_lldp_prem_manaddr_table,Fail,Mapped,2023-12-30 03:04:49,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_rem_man_addr_table,system/test_lldp.py,"V1, V2",
19,gw2,Regression,FtOpSoSwlldpFn011,Fail,Mapped,2023-12-30 03:04:49,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
20,gw2,Regression,FtOpSoSwlldpFn010,Fail,Mapped,2023-12-30 03:04:49,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
21,gw2,Regression,FtOpSoSwlldpFn009,Fail,Mapped,2023-12-30 03:04:49,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
22,gw2,Regression,FtOpSoSwlldpFn008,Fail,Mapped,2023-12-30 03:04:49,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
23,gw2,Regression,FtOpSoSwlldpFn004,Fail,Mapped,2023-12-30 03:04:49,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
24,gw2,Regression,FtOpSoSwlldpFn013,Fail,Mapped,2023-12-30 03:04:50,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_docker_restart,system/test_lldp.py,"V1, V2",
25,gw2,Regression,lldp_verify_counters,Fail,Mapped,2023-12-30 03:04:50,module configuration failed. LLDP neighbors information is not found after polling @5445,test_lldp_verify_counters,system/test_lldp.py,"V1, V2",
26,gw2,Regression,ft_lldp_with_remote_server,Fail,Mapped,2023-12-30 03:04:50,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_with_remote_server,system/test_lldp.py,"V1, V2",
27,gw2,Regression,FtOpSoSyInIpFn002,Fail,Mapped,2023-12-30 03:09:22,interface is down on DUT ['Ethernet16'],test_ft_port_fn_verify_shut_noshut,system/test_interface.py,"V1, V2",
28,gw3,Regression,ft_ssh_service_disable,Pass,Mapped,2023-12-30 03:10:35,Test case passed,test_ft_ssh_service_disable,system/test_ssh.py,"V3, V4",
29,gw6,Instrumentation,ft_sf_wm_telemetry_interval,Pass,Mapped,2023-12-30 03:17:07,verification of configured telemetry interval and reset to default interval is successful,test_ft_watermark_telemetry_interval,system/test_snapshot.py,V2,
30,gw6,Instrumentation Enhancements,ft_sf_snapshot_tam_Error_Logs,Fail,SubTest,2023-12-30 03:17:07,Error logs are getting generated on the device,test_ft_watermark_telemetry_interval,system/test_snapshot.py,V2,
31,gw5,Regression,ft_snmp_sysName,Fail,Mapped,2023-12-30 03:18:04,sysname output is not in sync between system and snmp,test_ft_snmp_sysName,system/test_snmp.py,V1,
32,gw5,Regression,ft_snmp_test_syUpTime,Pass,Mapped,2023-12-30 03:18:10,Test case passed,test_ft_snmp_test_syUpTime,system/test_snmp.py,V1,
33,gw5,Regression,ft_snmp_sysDescr,Pass,Mapped,2023-12-30 03:18:17,Test case passed,test_ft_snmp_sysDescr,system/test_snmp.py,V1,
34,gw5,Regression,FtOpSoSySnFn008,Pass,Mapped,2023-12-30 03:18:28,Test case passed,test_ft_snmp_mib_2,system/test_snmp.py,V1,
35,gw5,Regression,FtOpSoSySnFn009,Pass,Mapped,2023-12-30 03:18:33,Test case passed,test_ft_snmp_if_mib_all,system/test_snmp.py,V1,
36,gw5,Regression,FtOpSoSySnFn010,Pass,Mapped,2023-12-30 03:18:38,Test case passed,test_ft_snmp_entity_mib_all,system/test_snmp.py,V1,
37,gw5,Regression,FtOpSoSySnFn013,Pass,Mapped,2023-12-30 03:18:43,Test case passed,test_ft_snmp_dot1q_dot1db_mib,system/test_snmp.py,V1,
38,gw5,Regression,FtOpSoSySnFn012,Pass,Mapped,2023-12-30 03:18:43,Test case passed,test_ft_snmp_dot1q_dot1db_mib,system/test_snmp.py,V1,
39,gw5,Regression,FtOpSoSySnFn015,Pass,Mapped,2023-12-30 03:18:59,Test case passed,test_ft_snmp_root_node_walk,system/test_snmp.py,V1,
40,gw5,Regression,FtOpSoSySnFn016,Pass,Mapped,2023-12-30 03:19:09,Test case passed,test_ft_snmp_ipAddressRowStatus_ipv6,system/test_snmp.py,V1,
41,gw5,Regression,FtOpSoSySnFn017,Pass,Mapped,2023-12-30 03:19:13,Test case passed,test_ft_snmp_ipAddressStorageType_ipv6,system/test_snmp.py,V1,
42,gw5,Regression,FtOpSoSySnFn020,Pass,Mapped,2023-12-30 03:19:18,Test case passed,test_ft_snmp_ipv6_If_Forward_default_HopLimit,system/test_snmp.py,V1,
43,gw5,Regression,FtOpSoSySnFn021,Pass,Mapped,2023-12-30 03:19:22,Test case passed,test_ft_snmp_ipv6scope_index_table,system/test_snmp.py,V1,
44,gw5,Regression,test_snmp_ip_forward_table,Pass,Mapped,2023-12-30 03:19:30,Test case passed,test_ft_snmp_ip_forward_table,system/test_snmp.py,V1,
45,gw5,SNMP Agent Optimization,ft_snmp_ifXTable,Pass,Mapped,2023-12-30 03:19:35,Test case passed,test_ft_snmp_ifx_table,system/test_snmp.py,V1,
46,gw5,SNMP Agent Optimization,ft_snmp_ip_System_Stats_Table,Pass,Mapped,2023-12-30 03:19:40,Test case passed,test_ft_snmp_ip_System_Stats_Table,system/test_snmp.py,V1,
47,gw5,SNMP Agent Optimization,ft_snmp_ip_IfStats_Table,Pass,Mapped,2023-12-30 03:19:45,Test case passed,test_ft_snmp_ip_IfStats_Table,system/test_snmp.py,V1,
48,gw5,SNMP Agent Optimization,ft_snmp_ip_Address_Table,Pass,Mapped,2023-12-30 03:19:49,Test case passed,test_ft_snmp_ip_Address_Table,system/test_snmp.py,V1,
49,gw3,Regression,ft_ssh_add_user_verify,Fail,Mapped,2023-12-30 03:19:49,Test case Failed.,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
50,gw3,Control Plane ACL,test_ft_controlplane_acl_service_sshv4,Pass,SubTest,2023-12-30 03:19:49,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
51,gw3,Control Plane ACL,test_ft_controlplane_acl_service_sshv6,Pass,SubTest,2023-12-30 03:19:49,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
52,gw3,Control Plane ACL,test_ft_controlplane_acl_service_snmp,Fail,SubTest,2023-12-30 03:19:49,SNMP output is not found after walk of with control plane ACL service SNMP after reboot OID,test_ft_ssh_add_user_verify,system/test_ssh.py,"V3, V4",
53,gw5,SNMP Agent Optimization,ft_snmp_ip_NetToPhysical_Table,Pass,Mapped,2023-12-30 03:19:54,Test case passed,test_ft_snmp_ip_NetToPhysical_Table,system/test_snmp.py,V1,
54,gw5,SNMP Agent Optimization,ft_snmp_icmp_Msgs,Pass,Mapped,2023-12-30 03:19:58,Test case passed,test_ft_snmp_icmp_Msgs,system/test_snmp.py,V1,
55,gw3,Regression,CETA_SONIC_67575,Pass,Mapped,2023-12-30 03:20:13,Test case passed,test_ft_verify_logs_at_the_time_of_ssh_login_success,system/test_ssh.py,"V3, V4",
56,gw5,SNMP Agent Optimization,ft_snmp_tcp_mib,Pass,Mapped,2023-12-30 03:20:18,Test case passed,test_ft_snmp_tcp_mib,system/test_snmp.py,V1,
57,gw5,SNMP Agent Optimization,ft_snmp_udp_mib,Pass,Mapped,2023-12-30 03:20:23,Test case passed,test_ft_snmp_udp_mib,system/test_snmp.py,V1,
58,gw5,SNMP Agent Optimization,ft_snmp_snmpv2_mib,Pass,Mapped,2023-12-30 03:20:28,Test case passed,test_ft_snmp_snmpv2_mib,system/test_snmp.py,V1,
59,gw5,SNMP Agent Optimization,ft_snmp_host_resource_mib,Pass,Mapped,2023-12-30 03:20:32,Test case passed,test_ft_snmp_host_resource_mib,system/test_snmp.py,V1,
60,gw5,SNMP Agent Optimization,ft_snmp_framework_mib,Pass,Mapped,2023-12-30 03:20:37,Test case passed,test_ft_snmp_framework_mib,system/test_snmp.py,V1,
61,gw6,Regression,ft_tacacsauth_enable_pamfile_created,Fail,Mapped,2023-12-30 03:20:41,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V2,
62,gw6,Regression,ft_tacacs_ssh_login,Fail,Mapped,2023-12-30 03:20:41,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V2,
63,gw6,Regression,ft_tacacs_single_server_for_auth,Fail,Mapped,2023-12-30 03:20:41,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V2,
64,gw6,Regression,ft_tacacs_default_login,Fail,Mapped,2023-12-30 03:20:41,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V2,
65,gw6,Regression,executing_server_key_in_appropriate_mode,Fail,Mapped,2023-12-30 03:20:41,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V2,
66,gw6,Regression,auth_shared_keys ,Fail,Mapped,2023-12-30 03:20:41,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V2,
67,gw5,SNMP Agent Optimization,ft_snmp_mpd_mib,Pass,Mapped,2023-12-30 03:20:42,Test case passed,test_ft_snmp_mpd_mib,system/test_snmp.py,V1,
68,gw5,SNMP Agent Optimization,ft_snmp_target_mib,Pass,Mapped,2023-12-30 03:20:46,Test case passed,test_ft_snmp_target_mib,system/test_snmp.py,V1,
69,gw5,SNMP Agent Optimization,ft_snmp_notification_mib,Pass,Mapped,2023-12-30 03:20:51,Test case passed,test_ft_snmp_notification_mib,system/test_snmp.py,V1,
70,gw5,SNMP Agent Optimization,ft_snmp_user_based_sm_mib,Pass,Mapped,2023-12-30 03:20:55,Test case passed,test_ft_snmp_user_based_sm_mib,system/test_snmp.py,V1,
71,gw5,SNMP Agent Optimization,ft_snmp_view_based_acm_mib,Pass,Mapped,2023-12-30 03:21:00,Test case passed,test_ft_snmp_view_based_acm_mib,system/test_snmp.py,V1,
72,gw5,SNMP Agent Optimization,ft_snmp_ent_physical_table,Pass,Mapped,2023-12-30 03:21:04,Test case passed,test_ft_snmp_ent_physical_table,system/test_snmp.py,V1,
73,gw5,SNMP Agent Optimization,ft_snmp_dot3_stats_table,Pass,Mapped,2023-12-30 03:21:09,Test case passed,test_ft_snmp_dot3_stats_table,system/test_snmp.py,V1,
74,gw5,SNMP Agent Optimization,ft_net_snmp_agent_mib,Pass,Mapped,2023-12-30 03:21:14,Test case passed,test_ft_net_snmp_agent_mib,system/test_snmp.py,V1,
75,gw5,SNMP Agent Optimization,ft_net_snmp_vacm_mib,Pass,Mapped,2023-12-30 03:21:19,Test case passed,test_ft_net_snmp_vacm_mib,system/test_snmp.py,V1,
76,gw5,SNMP Agent Optimization,ft_snmp_ucd_diskio_mib,Pass,Mapped,2023-12-30 03:21:23,Test case passed,test_ft_snmp_ucd_diskio_mib,system/test_snmp.py,V1,
77,gw5,SNMP Agent Optimization,ft_snmp_ucd_la_table,Pass,Mapped,2023-12-30 03:21:28,Test case passed,test_ft_snmp_ucd_la_table,system/test_snmp.py,V1,
78,gw5,SNMP Agent Optimization,ft_snmp_ucd_system_stats,Pass,Mapped,2023-12-30 03:21:32,Test case passed,test_ft_snmp_ucd_system_stats,system/test_snmp.py,V1,
79,gw5,SNMP MIB and Traps,SNMPQBr003,Fail,Mapped,2023-12-30 03:21:38,SNMP output is not found after walk of dot1qTpFdbPort OID,test_ft_snmp_dot1q_tp_fdb_port,system/test_snmp.py,V1,
80,gw5,SNMP MIB and Traps,SNMPQBr002,Pass,Mapped,2023-12-30 03:21:43,Test case passed,test_ft_snmp_dot1q_tp_fdb_address,system/test_snmp.py,V1,
81,gw5,In-Memory Debug Log,FtOpSoSysImLogFn012,EnvFail,Mapped,2023-12-30 03:22:02,Test case Failed Couldn't get the snmptrapd process details from snmp trap server. Please check the snmp trap server process in the server.,test_ft_snmp_coldstart_trap,system/test_snmp.py,V1,
82,gw5,SNMP MIB and Traps,SNMPTrap004,EnvFail,Mapped,2023-12-30 03:22:02,Test case Failed Couldn't get the snmptrapd process details from snmp trap server. Please check the snmp trap server process in the server.,test_ft_snmp_coldstart_trap,system/test_snmp.py,V1,
83,gw5,Regression,FtOpSoSySnFn023,Fail,Mapped,2023-12-30 03:22:21,sysname output is not in sync between system and snmp after docker restart,test_ft_snmp_docker_restart,system/test_snmp.py,V1,
84,gw6,Regression,ft_ntp_message_log_display_with_correct_time,Pass,Mapped,2023-12-30 03:29:22,Test case passed,test_ft_ntp_disable_enable_with_message_log,system/test_ntp.py,V2,
85,gw6,Regression,ft_ntp_disable_ntp_enable_ntp,Pass,Mapped,2023-12-30 03:29:22,Test case passed,test_ft_ntp_disable_enable_with_message_log,system/test_ntp.py,V2,
86,gw6,Regression,ft_ntp_existsconfig,Pass,Mapped,2023-12-30 03:29:32,Test case passed,test_ntp_exists_config,system/test_ntp.py,V2,
