2023-12-25 00:53:38,412 T0000: NOTICE WORKER = gw3
2023-12-25 00:53:38,412 T0000: NOTICE using testbed file /data/work/logs/docker-master-440433-l3/testbed_1_2_2.yaml
2023-12-25 00:53:38,412 T0000: NOTICE Execution Start Time: 2023-12-25 00:53:38.411203
2023-12-25 00:53:38,412 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-440433-l3/gw3
2023-12-25 00:53:38,994 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-25 00:53:38,994 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 32.5%
2023-12-25 00:53:38,994 T0000: NOTICE ROOT_PATH: /repo
2023-12-25 00:53:38,994 T0000: NOTICE Python: 3.8.10
2023-12-25 00:53:38,994 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D2T1:4
2023-12-25 00:53:38,994 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-25 00:53:38,994 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-25-00-51-08 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-440433-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-440433-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-440433-l3 --noop --feature-group master
2023-12-25 00:53:39,624 T0000: DEBUG 'errors' not set in properties for V1 assuming 'default'
2023-12-25 00:53:39,624 T0000: DEBUG 'errors' not set in properties for V2 assuming 'default'
2023-12-25 00:53:39,624 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-25 00:53:39,624 T0000: WARN  Registering Topology
2023-12-25 00:53:39,644 T0000: INFO  Connecting all devices
2023-12-25 00:53:39,645 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8'] skip: False
2023-12-25 00:53:40,107 T0005: INFO  [D1-V1] Connecting to device (V1): sonic_ssh: 172.18.0.2:22 ..
2023-12-25 00:53:40,107 T0005: INFO  [D1-V1] TRY Authentication: 172.18.0.2:22 admin YourPaSsWoRd
2023-12-25 00:53:40,112 T0006: INFO  [D2-V2] Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2023-12-25 00:53:40,112 T0006: INFO  [D2-V2] TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2023-12-25 00:53:40,682 T0000: INFO  TG Scapy Init
2023-12-25 00:53:40,682 T0000: INFO  TG Base Init skip: False
2023-12-25 00:53:40,732 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-25 00:53:40,847 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_25_00_53_40_762402/gw3/default.log
2023-12-25 00:53:40,854 T0000: DEBUG REQ: tg_connect(port_list=['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8'])
2023-12-25 00:53:45,318 T0005: DEBUG [D1-V1] Connected ...
2023-12-25 00:53:45,324 T0006: DEBUG [D2-V2] Connected ...
2023-12-25 00:53:46,150 T0006: INFO  [D2-V2] Prompt at the connection start: 'admin@V2:~$' 
2023-12-25 00:53:46,154 T0006: AUDIT [D2-V2] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-25 00:53:46,157 T0005: INFO  [D1-V1] Prompt at the connection start: 'admin@V1:~$' 
2023-12-25 00:53:46,158 T0005: AUDIT [D1-V1] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-25 00:53:46,565 T0006: INFO  [D2-V2] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-25 00:53:46,570 T0005: INFO  [D1-V1] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-25 00:53:46,830 T0006: INFO  [D2-V2]  00:53:46 up 17 days,  1:55,  1 user,  load average: 3.84, 9.34, 8.63
2023-12-25 00:53:46,830 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:53:46,839 T0006: AUDIT [D2-V2] cat /proc/uptime
2023-12-25 00:53:46,843 T0005: INFO  [D1-V1]  00:53:46 up 17 days,  1:55,  1 user,  load average: 3.84, 9.34, 8.63
2023-12-25 00:53:46,843 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:53:46,845 T0005: AUDIT [D1-V1] cat /proc/uptime
2023-12-25 00:53:47,246 T0006: INFO  [D2-V2] FCMD: cat /proc/uptime
2023-12-25 00:53:47,251 T0005: INFO  [D1-V1] FCMD: cat /proc/uptime
2023-12-25 00:53:47,502 T0006: INFO  [D2-V2] 1475701.24 116430459.22
2023-12-25 00:53:47,502 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:53:47,504 T0006: INFO  [D2-V2] UPTIME: 1475701.24
2023-12-25 00:53:47,505 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:47,510 T0005: INFO  [D1-V1] 1475701.25 116430459.56
2023-12-25 00:53:47,510 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:53:47,514 T0005: INFO  [D1-V1] UPTIME: 1475701.25
2023-12-25 00:53:47,514 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:47,917 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:47,924 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:48,532 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:53:48,533 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:53:48,535 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:48,537 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:48,537 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:48,584 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:53:48,585 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:53:48,587 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:48,588 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:48,589 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:52,024 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/1": "port-1", "1/2": "port-2", "1/3": "port-3", "1/4": "port-4", "1/5": "port-5", "1/6": "port-6", "1/7": "port-7", "1/8": "port-8"}, "status": 1}
2023-12-25 00:53:52,038 T0000: INFO  TG Connection: Success
2023-12-25 00:53:52,038 T0000: INFO  TG Connect...done
2023-12-25 00:53:53,543 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:53,594 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:53,953 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:54,001 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:54,610 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:53:54,610 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:53:54,612 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:54,613 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:54,614 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:54,616 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:53:54,616 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:53:54,618 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:54,621 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:53:54,621 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:53:59,619 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:53:59,626 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,026 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,033 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,687 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:00,687 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:00,690 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,692 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:00,692 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:00,694 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:00,695 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:00,697 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:00,699 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:00,699 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:05,697 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:05,704 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,103 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,111 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,764 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:06,765 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:06,767 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,769 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:06,769 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:06,771 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:06,771 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:06,774 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:06,775 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:06,775 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:11,772 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:11,781 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,178 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,187 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,797 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:12,797 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:12,799 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,801 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:12,802 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:12,839 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:12,839 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:12,842 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:12,843 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:12,844 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:17,807 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:17,849 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,215 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,256 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,866 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:18,866 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:18,869 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,871 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:18,871 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:18,875 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:18,875 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:18,878 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:18,880 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:18,880 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:23,877 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:23,885 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,284 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,292 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,895 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:24,896 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:24,900 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,901 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:24,901 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:24,903 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:24,903 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:24,906 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:24,908 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:24,908 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:29,905 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:29,912 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,312 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,319 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,923 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:30,923 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:30,926 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,929 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:30,929 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:30,931 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:30,931 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:30,934 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:30,936 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:30,936 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:35,933 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:35,941 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,340 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,349 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,950 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:36,950 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:36,953 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,955 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:36,955 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:36,959 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:36,959 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:36,962 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:36,964 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:36,964 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:41,961 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:41,968 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,367 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,375 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,975 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:42,976 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:42,978 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,980 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:42,980 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:42,985 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:42,986 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:42,988 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:42,990 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:42,990 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:47,985 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:47,991 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:48,392 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:48,398 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:49,002 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:49,002 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:49,005 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:49,007 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:49,007 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:49,010 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:49,010 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:49,012 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:49,013 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:49,013 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:54,013 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:54,017 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:54,420 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:54,427 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:55,088 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:54:55,088 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:54:55,090 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:54:55,091 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:54:55,093 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:55,094 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:54:55,096 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:55,096 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:54:55,097 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:54:55,097 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:00,100 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,101 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,515 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:00,519 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:01,132 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:01,133 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:01,135 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:01,136 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:01,138 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:01,141 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:01,142 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:01,143 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:01,143 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:01,143 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:06,144 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,148 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,551 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:06,557 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:07,265 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:07,265 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:07,268 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:07,271 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:07,271 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:07,274 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:07,274 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:07,276 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:07,277 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:07,277 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:12,277 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:12,281 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:12,683 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:12,688 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:13,293 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:13,293 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:13,296 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:13,298 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:13,298 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:13,300 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:13,301 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:13,303 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:13,305 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:13,305 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:18,301 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:18,309 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:18,708 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:18,716 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:19,318 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:19,319 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:19,321 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:19,323 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:19,323 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:19,326 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:19,327 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:19,329 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:19,331 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:19,331 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:24,328 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:24,337 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:24,734 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:24,744 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:25,446 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:25,446 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:25,450 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:25,451 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:25,452 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:25,455 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:25,456 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:25,458 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:25,460 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:25,460 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:30,457 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:30,465 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:30,864 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:30,871 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:31,526 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:31,527 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:31,529 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:31,535 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:31,536 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:31,538 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:31,538 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:31,540 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:31,541 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:31,541 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:36,544 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:36,547 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:36,956 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:36,962 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:37,573 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:37,574 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:37,576 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:37,577 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:37,577 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:37,721 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:37,722 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:37,724 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:37,725 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:37,725 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:42,581 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:42,729 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:42,987 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:43,137 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:43,648 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-25 00:55:43,648 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:43,651 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:43,652 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:43,652 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:43,850 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 00:55:43,850 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:43,853 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 00:55:43,855 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 00:55:43,855 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-25 00:55:48,658 T0006: ERROR [D2-V2] Failed to read hostname from vtysh - assuming sonic
2023-12-25 00:55:48,661 T0006: INFO  [D2-V2] Base Prompt: sonic
2023-12-25 00:55:48,663 T0006: DEBUG [D2-V2] Wait for system ready Ref: 866
2023-12-25 00:55:48,862 T0005: ERROR [D1-V1] Failed to read hostname from vtysh - assuming sonic
2023-12-25 00:55:48,863 T0005: INFO  [D1-V1] Base Prompt: sonic
2023-12-25 00:55:48,864 T0005: DEBUG [D1-V1] Wait for system ready Ref: 866
2023-12-25 00:55:49,069 T0006: INFO  [D2-V2] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:49,269 T0005: INFO  [D1-V1] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:49,327 T0006: INFO  [D2-V2] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:49,327 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:49,330 T0006: WARN  [D2-V2] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-25 00:55:49,331 T0006: INFO  [D2-V2] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:49,526 T0005: INFO  [D1-V1] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-25 00:55:49,527 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:49,530 T0005: WARN  [D1-V1] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-25 00:55:49,532 T0005: INFO  [D1-V1] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:53,155 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2] 
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2] Remote CMD: 'show platform summary'
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]     from show.main import cli
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]     if is_gearbox_configured():
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:53,157 T0006: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2] 
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2] Remote CMD: 'sudo show interfaces status '
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]     from show.main import cli
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]     if is_gearbox_configured():
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:53,158 T0006: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:53,159 T0006: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,159 T0006: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:53,159 T0006: INFO  [D2-V2] 
2023-12-25 00:55:53,159 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-25 00:55:53,159 T0006: ERROR [D2-V2] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:53,368 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:53,370 T0005: INFO  [D1-V1] 
2023-12-25 00:55:53,370 T0005: INFO  [D1-V1] Remote CMD: 'show platform summary'
2023-12-25 00:55:53,370 T0005: INFO  [D1-V1] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:53,370 T0005: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:53,371 T0005: INFO  [D1-V1]     from show.main import cli
2023-12-25 00:55:53,371 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:53,371 T0005: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-25 00:55:53,371 T0005: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,372 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:53,372 T0005: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:53,372 T0005: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:53,372 T0005: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:53,372 T0005: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,373 T0005: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:53,373 T0005: INFO  [D1-V1] 
2023-12-25 00:55:53,373 T0005: INFO  [D1-V1] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-25 00:55:53,373 T0005: INFO  [D1-V1] Remote CMD: 'sudo show interfaces status '
2023-12-25 00:55:53,373 T0005: INFO  [D1-V1] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 00:55:53,373 T0005: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 00:55:53,373 T0005: INFO  [D1-V1]     from show.main import cli
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 00:55:53,374 T0005: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 00:55:53,375 T0005: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 00:55:53,375 T0005: INFO  [D1-V1] 
2023-12-25 00:55:53,375 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 00:55:53,376 T0005: ERROR [D1-V1] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 00:55:53,376 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-25 00:55:53,376 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-25 00:55:53,377 T0004: ERROR [D1-V1] Failed to connect to device
2023-12-25 00:55:53,377 T0004: ERROR [D2-V2] Failed to connect to device
2023-12-25 00:55:53,378 T0000: ERROR Failed to connect (['V1', 'V2'])
2023-12-25 00:55:53,378 T0000: INFO  --FINISH--RUN--4 @559
