ordering items took 0:00:01
Tests considered 72 and ignored 317
2023-12-27 00:44:36,590 T0000: NOTICE WORKER = gw3
2023-12-27 00:44:36,591 T0000: NOTICE using testbed file /data/work/logs/docker-master-441696-l3/testbed_1_2_2.yaml
2023-12-27 00:44:36,591 T0000: NOTICE Execution Start Time: 2023-12-27 00:44:36.589104
2023-12-27 00:44:36,591 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-441696-l3/gw3
2023-12-27 00:44:37,113 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-27 00:44:37,113 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 35.9%
2023-12-27 00:44:37,113 T0000: NOTICE ROOT_PATH: /repo
2023-12-27 00:44:37,113 T0000: NOTICE Python: 3.8.10
2023-12-27 00:44:37,113 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D2T1:4
2023-12-27 00:44:37,113 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-27 00:44:37,113 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-27-00-42-05 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-441696-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-441696-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-441696-l3 --noop --feature-group master
2023-12-27 00:44:37,725 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2023-12-27 00:44:37,725 T0000: DEBUG 'errors' not set in properties for V4 assuming 'default'
2023-12-27 00:44:37,725 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-27 00:44:37,726 T0000: WARN  Registering Topology
2023-12-27 00:44:37,746 T0000: INFO  Connecting all devices
2023-12-27 00:44:37,747 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'] skip: False
2023-12-27 00:44:38,251 T0005: INFO  [D1-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2023-12-27 00:44:38,252 T0005: INFO  [D1-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2023-12-27 00:44:38,256 T0006: INFO  [D2-V4] Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2023-12-27 00:44:38,257 T0006: INFO  [D2-V4] TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2023-12-27 00:44:38,785 T0000: INFO  TG Scapy Init
2023-12-27 00:44:38,785 T0000: INFO  TG Base Init skip: False
2023-12-27 00:44:38,795 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-27 00:44:38,919 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_27_00_44_38_820464/gw3/default.log
2023-12-27 00:44:38,925 T0000: DEBUG REQ: tg_connect(port_list=['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'])
2023-12-27 00:44:43,461 T0005: DEBUG [D1-V3] Connected ...
2023-12-27 00:44:43,465 T0006: DEBUG [D2-V4] Connected ...
2023-12-27 00:44:44,296 T0006: INFO  [D2-V4] Prompt at the connection start: 'admin@V4:~$' 
2023-12-27 00:44:44,298 T0006: AUDIT [D2-V4] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-27 00:44:44,299 T0005: INFO  [D1-V3] Prompt at the connection start: 'admin@V3:~$' 
2023-12-27 00:44:44,300 T0005: AUDIT [D1-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-27 00:44:44,711 T0006: INFO  [D2-V4] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-27 00:44:44,718 T0005: INFO  [D1-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-27 00:44:44,973 T0006: INFO  [D2-V4]  00:44:44 up 19 days,  1:46,  1 user,  load average: 11.28, 17.21, 11.81
2023-12-27 00:44:44,974 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:44:44,982 T0006: AUDIT [D2-V4] cat /proc/uptime
2023-12-27 00:44:44,985 T0005: INFO  [D1-V3]  00:44:44 up 19 days,  1:46,  1 user,  load average: 11.28, 17.21, 11.81
2023-12-27 00:44:44,986 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:44:44,988 T0005: AUDIT [D1-V3] cat /proc/uptime
2023-12-27 00:44:45,388 T0006: INFO  [D2-V4] FCMD: cat /proc/uptime
2023-12-27 00:44:45,393 T0005: INFO  [D1-V3] FCMD: cat /proc/uptime
2023-12-27 00:44:45,644 T0006: INFO  [D2-V4] 1648001.99 129986633.38
2023-12-27 00:44:45,645 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:44:45,647 T0006: INFO  [D2-V4] UPTIME: 1648001.99
2023-12-27 00:44:45,647 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:45,652 T0005: INFO  [D1-V3] 1648002.00 129986634.03
2023-12-27 00:44:45,652 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:44:45,654 T0005: INFO  [D1-V3] UPTIME: 1648002.00
2023-12-27 00:44:45,655 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:46,056 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:46,061 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:46,666 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:44:46,666 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:44:46,669 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:46,671 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:44:46,671 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:44:46,673 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:46,674 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:44:46,675 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:46,676 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:46,676 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:44:51,679 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:51,680 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:51,703 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12", "1/13": "port-13", "1/14": "port-14", "1/15": "port-15", "1/16": "port-16"}, "status": 1}
2023-12-27 00:44:51,715 T0000: INFO  TG Connection: Success
2023-12-27 00:44:51,715 T0000: INFO  TG Connect...done
2023-12-27 00:44:52,094 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:52,101 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:52,710 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:44:52,710 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:44:52,712 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:44:52,713 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:44:52,714 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:52,716 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:52,718 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:52,718 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:44:52,719 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:52,720 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:44:57,724 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:57,725 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:58,137 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:58,143 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:58,804 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:44:58,804 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:44:58,807 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:44:58,807 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:44:58,810 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:58,813 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:44:58,814 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:58,814 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:44:58,815 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:44:58,815 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:03,820 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:03,821 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:04,233 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:04,239 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:04,897 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:04,897 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:04,900 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:04,902 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:04,903 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:04,906 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:04,906 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:04,909 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:04,911 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:04,911 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:09,911 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:09,915 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:10,318 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:10,324 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:10,982 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:10,982 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:10,985 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:10,988 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:10,989 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:10,991 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:10,991 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:10,992 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:10,993 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:10,993 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:15,995 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:15,996 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:16,409 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:16,415 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:17,026 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:17,026 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:17,029 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:17,029 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:17,031 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:17,033 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:17,035 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:17,035 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:17,037 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:17,037 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:22,039 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:22,041 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:22,451 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:22,458 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:23,068 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:23,068 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:23,072 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:23,073 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:23,076 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:23,078 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:23,079 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:23,079 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:23,081 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:23,081 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:28,085 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:28,087 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:28,499 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:28,506 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:29,164 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:29,165 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:29,169 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:29,170 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:29,172 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:29,174 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:29,176 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:29,176 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:29,178 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:29,178 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:34,182 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:34,183 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:34,597 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:34,602 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:35,261 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:35,261 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:35,264 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:35,264 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:35,267 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:35,269 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:35,271 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:35,272 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:35,273 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:35,273 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:40,276 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:40,276 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:40,690 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:40,696 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:41,358 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:41,358 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:41,361 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:41,362 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:41,363 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:41,364 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:41,365 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:41,365 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:41,366 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:41,366 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:46,371 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:46,372 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:46,785 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:46,792 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:47,502 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:47,502 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:47,504 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:47,505 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:47,505 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:47,551 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:47,551 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:47,554 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:47,555 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:47,556 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:52,510 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:52,559 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:52,918 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:52,967 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:53,578 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:53,578 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:53,581 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:53,582 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:53,583 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:53,626 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:53,627 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:53,629 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:53,631 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:53,631 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:58,588 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:58,636 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:58,995 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:59,043 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:59,656 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:45:59,656 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:45:59,658 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:59,660 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:59,660 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:45:59,704 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:45:59,704 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:45:59,706 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:45:59,708 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:45:59,708 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:04,666 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:04,714 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:05,073 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:05,121 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:05,735 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:46:05,736 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:05,740 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:05,742 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:05,742 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:05,782 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:46:05,782 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:05,784 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:05,785 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:05,786 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:10,747 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:10,791 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:11,153 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:11,198 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:11,764 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:46:11,765 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:11,768 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:11,770 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:11,770 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:11,808 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:46:11,808 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:11,811 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:11,813 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:11,813 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:16,776 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:16,815 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:17,183 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:17,222 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:17,795 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:46:17,795 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:17,797 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:17,799 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:17,800 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:17,833 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:46:17,833 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:17,838 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:17,840 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:17,840 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:22,803 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:22,845 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:23,210 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:23,252 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:23,863 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:46:23,863 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:23,866 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:23,868 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:23,868 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:23,870 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:46:23,871 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:23,873 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:23,875 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:23,875 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:28,874 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:28,881 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:29,282 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:29,288 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:30,204 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:46:30,204 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:30,208 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:30,209 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:30,210 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:30,546 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:46:30,546 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:30,549 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:30,551 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:30,551 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:35,215 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:35,555 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:35,624 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:35,965 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:36,336 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:46:36,337 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:36,338 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:36,339 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:36,339 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:36,829 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:46:36,829 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:36,832 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:36,834 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:36,835 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:41,345 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:41,752 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:41,840 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:42,245 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:42,462 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2023-12-27 00:46:42,462 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:42,464 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:42,465 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:42,465 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:42,903 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2023-12-27 00:46:42,903 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:42,905 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-27 00:46:42,907 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2023-12-27 00:46:42,907 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-27 00:46:47,471 T0005: ERROR [D1-V3] Failed to read hostname from vtysh - assuming sonic
2023-12-27 00:46:47,471 T0005: INFO  [D1-V3] Base Prompt: sonic
2023-12-27 00:46:47,472 T0005: DEBUG [D1-V3] Wait for system ready Ref: 866
2023-12-27 00:46:47,877 T0005: INFO  [D1-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-27 00:46:47,911 T0006: ERROR [D2-V4] Failed to read hostname from vtysh - assuming sonic
2023-12-27 00:46:47,912 T0006: INFO  [D2-V4] Base Prompt: sonic
2023-12-27 00:46:47,913 T0006: DEBUG [D2-V4] Wait for system ready Ref: 866
2023-12-27 00:46:48,134 T0005: INFO  [D1-V3] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-27 00:46:48,134 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:48,140 T0005: WARN  [D1-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-27 00:46:48,143 T0005: INFO  [D1-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:46:48,318 T0006: INFO  [D2-V4] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-27 00:46:48,576 T0006: INFO  [D2-V4] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-27 00:46:48,576 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:48,579 T0006: WARN  [D2-V4] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-27 00:46:48,580 T0006: INFO  [D2-V4] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:46:51,965 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:46:51,966 T0005: INFO  [D1-V3] 
2023-12-27 00:46:51,966 T0005: INFO  [D1-V3] Remote CMD: 'show platform summary'
2023-12-27 00:46:51,967 T0005: INFO  [D1-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-27 00:46:51,967 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-27 00:46:51,967 T0005: INFO  [D1-V3]     from show.main import cli
2023-12-27 00:46:51,967 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-27 00:46:51,967 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-27 00:46:51,967 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:51,967 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3] 
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-27 00:46:51,968 T0005: INFO  [D1-V3] Remote CMD: 'sudo show interfaces status '
2023-12-27 00:46:51,969 T0005: INFO  [D1-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-27 00:46:51,969 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2023-12-27 00:46:51,969 T0005: INFO  [D1-V3]     from show.main import cli
2023-12-27 00:46:51,969 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-27 00:46:51,969 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2023-12-27 00:46:51,969 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:51,969 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-27 00:46:51,970 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2023-12-27 00:46:51,970 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-27 00:46:51,970 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-27 00:46:51,970 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:51,970 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-27 00:46:51,970 T0005: INFO  [D1-V3] 
2023-12-27 00:46:51,970 T0005: INFO  [D1-V3] admin@V3:~$ 
2023-12-27 00:46:51,971 T0005: ERROR [D1-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:46:52,399 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:46:52,400 T0006: INFO  [D2-V4] 
2023-12-27 00:46:52,400 T0006: INFO  [D2-V4] Remote CMD: 'show platform summary'
2023-12-27 00:46:52,401 T0006: INFO  [D2-V4] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-27 00:46:52,401 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-27 00:46:52,401 T0006: INFO  [D2-V4]     from show.main import cli
2023-12-27 00:46:52,401 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-27 00:46:52,401 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2023-12-27 00:46:52,402 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:52,402 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-27 00:46:52,402 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2023-12-27 00:46:52,402 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-27 00:46:52,402 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-27 00:46:52,403 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:52,403 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-27 00:46:52,403 T0006: INFO  [D2-V4] 
2023-12-27 00:46:52,403 T0006: INFO  [D2-V4] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-27 00:46:52,403 T0006: INFO  [D2-V4] Remote CMD: 'sudo show interfaces status '
2023-12-27 00:46:52,403 T0006: INFO  [D2-V4] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-27 00:46:52,404 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2023-12-27 00:46:52,404 T0006: INFO  [D2-V4]     from show.main import cli
2023-12-27 00:46:52,404 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-27 00:46:52,404 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2023-12-27 00:46:52,404 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:52,404 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-27 00:46:52,404 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2023-12-27 00:46:52,405 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-27 00:46:52,405 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-27 00:46:52,405 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 00:46:52,405 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-27 00:46:52,405 T0006: INFO  [D2-V4] 
2023-12-27 00:46:52,405 T0006: INFO  [D2-V4] admin@V4:~$ 
2023-12-27 00:46:52,406 T0006: ERROR [D2-V4] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-27 00:46:52,407 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-27 00:46:52,407 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-27 00:46:52,409 T0004: ERROR [D1-V3] Failed to connect to device
2023-12-27 00:46:52,410 T0004: ERROR [D2-V4] Failed to connect to device
2023-12-27 00:46:52,411 T0000: ERROR Failed to connect (['V3', 'V4'])
2023-12-27 00:46:52,411 T0000: INFO  --FINISH--RUN--4 @559
