ordering items took 0:00:01
Tests considered 69 and ignored 320
2023-12-25 01:47:29,217 T0000: NOTICE WORKER = gw5
2023-12-25 01:47:29,217 T0000: NOTICE using testbed file /data/work/logs/docker-master-440433-l2/testbed_1_1_2.yaml
2023-12-25 01:47:29,217 T0000: NOTICE Execution Start Time: 2023-12-25 01:47:29.215747
2023-12-25 01:47:29,217 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-440433-l2/gw5
2023-12-25 01:47:29,701 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-25 01:47:29,701 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 33.0%
2023-12-25 01:47:29,701 T0000: NOTICE ROOT_PATH: /repo
2023-12-25 01:47:29,701 T0000: NOTICE Python: 3.8.10
2023-12-25 01:47:29,701 T0000: NOTICE Topology unknown: D1T1:4
2023-12-25 01:47:29,701 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-25 01:47:29,701 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-25-01-44-59 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-440433-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-440433-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-440433-l2 --noop --feature-group master
2023-12-25 01:47:30,313 T0000: DEBUG 'errors' not set in properties for V1 assuming 'default'
2023-12-25 01:47:30,313 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-25 01:47:30,313 T0000: WARN  Registering Topology
2023-12-25 01:47:30,329 T0000: INFO  Connecting all devices
2023-12-25 01:47:30,333 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/1', '1/2', '1/3', '1/4'] skip: False
2023-12-25 01:47:30,554 T0002: INFO  [D1-V1] Connecting to device (V1): sonic_ssh: 172.18.0.2:22 ..
2023-12-25 01:47:30,554 T0002: INFO  [D1-V1] TRY Authentication: 172.18.0.2:22 admin YourPaSsWoRd
2023-12-25 01:47:31,344 T0000: INFO  TG Scapy Init
2023-12-25 01:47:31,344 T0000: INFO  TG Base Init skip: False
2023-12-25 01:47:31,355 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-25 01:47:31,590 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_25_01_47_31_386485/gw5/default.log
2023-12-25 01:47:31,597 T0000: DEBUG REQ: tg_connect(port_list=['1/1', '1/2', '1/3', '1/4'])
2023-12-25 01:47:36,167 T0002: DEBUG [D1-V1] Connected ...
2023-12-25 01:47:36,991 T0002: INFO  [D1-V1] Prompt at the connection start: 'admin@V1:~$' 
2023-12-25 01:47:36,993 T0002: AUDIT [D1-V1] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-25 01:47:37,400 T0002: INFO  [D1-V1] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-25 01:47:37,657 T0002: INFO  [D1-V1]  01:47:37 up 17 days,  2:48,  1 user,  load average: 11.63, 17.17, 11.83
2023-12-25 01:47:37,657 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:47:37,665 T0002: AUDIT [D1-V1] cat /proc/uptime
2023-12-25 01:47:38,071 T0002: INFO  [D1-V1] FCMD: cat /proc/uptime
2023-12-25 01:47:38,232 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/1": "port-1", "1/2": "port-2", "1/3": "port-3", "1/4": "port-4"}, "status": 1}
2023-12-25 01:47:38,242 T0000: INFO  TG Connection: Success
2023-12-25 01:47:38,242 T0000: INFO  TG Connect...done
2023-12-25 01:47:38,329 T0002: INFO  [D1-V1] 1478935.39 116666658.37
2023-12-25 01:47:38,329 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:47:38,331 T0002: INFO  [D1-V1] UPTIME: 1478935.39
2023-12-25 01:47:38,332 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:38,740 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:39,350 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:47:39,351 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:47:39,353 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:39,356 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:47:39,356 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:47:44,362 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:44,769 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:45,380 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:47:45,381 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:47:45,383 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:45,385 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:47:45,386 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:47:50,391 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:50,799 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:51,409 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:47:51,410 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:47:51,412 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:51,414 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:47:51,414 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:47:56,420 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:56,827 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:57,437 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:47:57,437 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:47:57,439 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:47:57,440 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:47:57,440 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:02,446 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:02,856 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:03,467 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:03,467 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:03,470 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:03,472 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:03,473 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:08,478 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:08,886 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:09,547 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:09,547 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:09,550 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:09,552 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:09,552 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:14,555 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:14,962 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:15,573 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:15,574 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:15,576 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:15,579 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:15,579 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:20,585 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:20,992 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:21,604 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:21,605 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:21,607 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:21,609 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:21,610 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:26,615 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:27,021 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:27,631 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:27,631 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:27,634 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:27,636 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:27,636 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:32,639 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:33,046 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:33,707 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:33,707 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:33,710 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:33,712 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:33,712 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:38,718 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:39,125 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:39,735 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:39,736 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:39,738 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:39,739 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:39,739 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:44,743 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:45,151 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:45,762 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:45,762 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:45,765 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:45,767 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:45,767 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:50,773 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:51,180 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:51,842 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:51,842 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:51,845 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:51,846 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:51,847 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:48:56,851 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:57,258 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:57,869 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:48:57,870 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:48:57,872 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:48:57,874 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:48:57,875 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:49:02,880 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:03,288 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:03,899 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:49:03,899 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:03,902 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:03,904 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:49:03,904 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:49:08,910 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:09,317 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:09,929 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:49:09,929 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:09,932 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:09,934 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:49:09,934 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:49:14,939 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:15,345 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:16,057 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:49:16,057 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:16,060 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:16,062 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:49:16,063 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:49:21,068 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:21,476 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:22,238 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:49:22,238 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:22,241 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:22,243 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:49:22,243 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:49:27,246 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:27,651 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:28,258 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:49:28,259 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:28,261 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:28,264 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:49:28,264 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:49:33,270 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:33,678 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:34,391 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-25 01:49:34,391 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:34,392 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-25 01:49:34,394 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-25 01:49:34,394 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-25 01:49:39,402 T0002: ERROR [D1-V1] Failed to read hostname from vtysh - assuming sonic
2023-12-25 01:49:39,407 T0002: INFO  [D1-V1] Base Prompt: sonic
2023-12-25 01:49:39,410 T0002: DEBUG [D1-V1] Wait for system ready Ref: 866
2023-12-25 01:49:39,815 T0002: INFO  [D1-V1] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-25 01:49:40,071 T0002: INFO  [D1-V1] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-25 01:49:40,071 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:40,073 T0002: WARN  [D1-V1] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-25 01:49:40,074 T0002: INFO  [D1-V1] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 01:49:43,897 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 01:49:43,899 T0002: INFO  [D1-V1] 
2023-12-25 01:49:43,899 T0002: INFO  [D1-V1] Remote CMD: 'show platform summary'
2023-12-25 01:49:43,899 T0002: INFO  [D1-V1] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 01:49:43,899 T0002: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 01:49:43,899 T0002: INFO  [D1-V1]     from show.main import cli
2023-12-25 01:49:43,899 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 01:49:43,900 T0002: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-25 01:49:43,900 T0002: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 01:49:43,900 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 01:49:43,900 T0002: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-25 01:49:43,900 T0002: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 01:49:43,900 T0002: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 01:49:43,901 T0002: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 01:49:43,901 T0002: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 01:49:43,901 T0002: INFO  [D1-V1] 
2023-12-25 01:49:43,901 T0002: INFO  [D1-V1] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-25 01:49:43,901 T0002: INFO  [D1-V1] Remote CMD: 'sudo show interfaces status '
2023-12-25 01:49:43,901 T0002: INFO  [D1-V1] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-25 01:49:43,901 T0002: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-25 01:49:43,902 T0002: INFO  [D1-V1]     from show.main import cli
2023-12-25 01:49:43,902 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-25 01:49:43,902 T0002: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-25 01:49:43,902 T0002: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 01:49:43,902 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-25 01:49:43,902 T0002: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-25 01:49:43,902 T0002: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-25 01:49:43,903 T0002: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-25 01:49:43,903 T0002: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-25 01:49:43,903 T0002: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-25 01:49:43,903 T0002: INFO  [D1-V1] 
2023-12-25 01:49:43,903 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-25 01:49:43,903 T0002: ERROR [D1-V1] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-25 01:49:43,904 T0002: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-25 01:49:43,904 T0002: ERROR [D1-V1] Failed to connect to device
2023-12-25 01:49:43,905 T0000: ERROR Failed to connect (['V1'])
2023-12-25 01:49:43,905 T0000: INFO  --FINISH--RUN--4 @559
