ordering items took 0:00:01
Tests considered 72 and ignored 317
2023-12-31 00:58:02,714 T0000: NOTICE WORKER = gw6
2023-12-31 00:58:02,714 T0000: NOTICE using testbed file /data/work/logs/docker-master-444338-l3/testbed_1_1_3.yaml
2023-12-31 00:58:02,714 T0000: NOTICE Execution Start Time: 2023-12-31 00:58:02.712070
2023-12-31 00:58:02,714 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-444338-l3/gw6
2023-12-31 00:58:03,229 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-31 00:58:03,229 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 43.0%
2023-12-31 00:58:03,229 T0000: NOTICE ROOT_PATH: /repo
2023-12-31 00:58:03,230 T0000: NOTICE Python: 3.8.10
2023-12-31 00:58:03,230 T0000: NOTICE Topology unknown: D1T1:4
2023-12-31 00:58:03,230 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-31 00:58:03,230 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-31-00-53-15 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-444338-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-444338-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-444338-l3 --noop --feature-group master
2023-12-31 00:58:03,864 T0000: DEBUG 'errors' not set in properties for V1 assuming 'default'
2023-12-31 00:58:03,865 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-31 00:58:03,865 T0000: WARN  Registering Topology
2023-12-31 00:58:03,881 T0000: INFO  Connecting all devices
2023-12-31 00:58:03,885 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/1', '1/2', '1/3', '1/4'] skip: False
2023-12-31 00:58:04,100 T0002: INFO  [D1-V1] Connecting to device (V1): sonic_ssh: 172.18.0.2:22 ..
2023-12-31 00:58:04,100 T0002: INFO  [D1-V1] TRY Authentication: 172.18.0.2:22 admin YourPaSsWoRd
2023-12-31 00:58:04,897 T0000: INFO  TG Scapy Init
2023-12-31 00:58:04,897 T0000: INFO  TG Base Init skip: False
2023-12-31 00:58:04,906 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-31 00:58:05,013 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_31_00_58_04_936799/gw6/default.log
2023-12-31 00:58:05,024 T0000: DEBUG REQ: tg_connect(port_list=['1/1', '1/2', '1/3', '1/4'])
2023-12-31 00:58:09,434 T0002: DEBUG [D1-V1] Connected ...
2023-12-31 00:58:10,271 T0002: INFO  [D1-V1] Prompt at the connection start: 'admin@V1:~$' 
2023-12-31 00:58:10,273 T0002: AUDIT [D1-V1] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-31 00:58:10,681 T0002: INFO  [D1-V1] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-31 00:58:10,941 T0002: INFO  [D1-V1]  00:58:10 up 23 days,  2:01,  1 user,  load average: 8.99, 19.65, 16.14
2023-12-31 00:58:10,941 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:10,951 T0002: AUDIT [D1-V1] cat /proc/uptime
2023-12-31 00:58:11,102 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/1": "port-1", "1/2": "port-2", "1/3": "port-3", "1/4": "port-4"}, "status": 1}
2023-12-31 00:58:11,115 T0000: INFO  TG Connection: Success
2023-12-31 00:58:11,115 T0000: INFO  TG Connect...done
2023-12-31 00:58:11,357 T0002: INFO  [D1-V1] FCMD: cat /proc/uptime
2023-12-31 00:58:11,617 T0002: INFO  [D1-V1] 1994489.87 157247061.37
2023-12-31 00:58:11,617 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:11,621 T0002: INFO  [D1-V1] UPTIME: 1994489.87
2023-12-31 00:58:11,622 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:12,028 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:12,840 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:12,841 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:12,844 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:12,846 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:12,846 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:58:17,851 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:18,259 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:18,922 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:18,922 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:18,925 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:18,927 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:18,927 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:58:23,933 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:24,340 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:25,003 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:25,003 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:25,007 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:25,009 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:25,009 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:58:30,015 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:30,424 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:31,088 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:31,089 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:31,091 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:31,093 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:31,094 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:58:36,099 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:36,506 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:37,318 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:37,318 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:37,320 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:37,322 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:37,322 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:58:42,327 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:42,734 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:43,496 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:43,496 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:43,499 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:43,501 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:43,501 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:58:48,503 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:48,909 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:49,572 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:49,572 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:49,576 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:49,578 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:49,578 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:58:54,583 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:54,990 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:55,705 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:58:55,706 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:58:55,709 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:58:55,710 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:58:55,711 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:00,715 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:01,123 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:01,784 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:01,785 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:01,787 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:01,789 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:01,789 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:06,791 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:07,201 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:07,862 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:07,862 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:07,864 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:07,865 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:07,865 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:12,867 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:13,275 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:13,937 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:13,937 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:13,940 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:13,941 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:13,941 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:18,947 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:19,354 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:19,966 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:19,966 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:19,969 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:19,970 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:19,970 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:24,975 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:25,380 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:26,089 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:26,090 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:26,091 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:26,093 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:26,093 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:31,098 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:31,506 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:32,219 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:32,220 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:32,222 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:32,224 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:32,224 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:37,227 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:37,633 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:38,392 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:38,392 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:38,394 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:38,395 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:38,395 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:43,401 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:43,808 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:44,570 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:44,570 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:44,573 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:44,575 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:44,576 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:49,579 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:49,986 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:50,698 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:50,698 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:50,701 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:50,704 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:50,704 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 00:59:55,710 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:56,119 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:56,784 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 00:59:56,784 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 00:59:56,788 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 00:59:56,790 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 00:59:56,791 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:00:01,795 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:00:02,203 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:00:02,913 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:00:02,913 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:00:02,914 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:00:02,915 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:00:02,915 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:00:07,921 T0002: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:00:08,327 T0002: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:00:08,988 T0002: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:00:08,988 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:00:08,991 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:00:08,993 T0002: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:00:08,993 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:00:13,996 T0002: ERROR [D1-V1] Failed to read hostname from vtysh - assuming sonic
2023-12-31 01:00:13,998 T0002: INFO  [D1-V1] Base Prompt: sonic
2023-12-31 01:00:13,999 T0002: DEBUG [D1-V1] Wait for system ready Ref: 866
2023-12-31 01:00:14,405 T0002: INFO  [D1-V1] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-31 01:00:14,663 T0002: INFO  [D1-V1] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-31 01:00:14,663 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:00:14,668 T0002: WARN  [D1-V1] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-31 01:00:14,669 T0002: INFO  [D1-V1] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:00:18,488 T0002: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:00:18,489 T0002: INFO  [D1-V1] 
2023-12-31 01:00:18,489 T0002: INFO  [D1-V1] Remote CMD: 'show platform summary'
2023-12-31 01:00:18,489 T0002: INFO  [D1-V1] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 01:00:18,489 T0002: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 01:00:18,489 T0002: INFO  [D1-V1]     from show.main import cli
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 01:00:18,490 T0002: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1] 
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1] Remote CMD: 'sudo show interfaces status '
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1]     from show.main import cli
2023-12-31 01:00:18,491 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 01:00:18,492 T0002: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-31 01:00:18,492 T0002: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:00:18,492 T0002: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 01:00:18,492 T0002: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-31 01:00:18,492 T0002: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 01:00:18,492 T0002: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 01:00:18,492 T0002: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:00:18,493 T0002: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 01:00:18,493 T0002: INFO  [D1-V1] 
2023-12-31 01:00:18,493 T0002: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:00:18,494 T0002: ERROR [D1-V1] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:00:18,494 T0002: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-31 01:00:18,495 T0002: ERROR [D1-V1] Failed to connect to device
2023-12-31 01:00:18,495 T0000: ERROR Failed to connect (['V1'])
2023-12-31 01:00:18,496 T0000: INFO  --FINISH--RUN--4 @559
