2023-12-31 01:49:52,642 T0000: NOTICE WORKER = gw2
2023-12-31 01:49:52,642 T0000: NOTICE using testbed file /data/work/logs/docker-master-444338-l2/testbed_1_2_1.yaml
2023-12-31 01:49:52,642 T0000: NOTICE Execution Start Time: 2023-12-31 01:49:52.641125
2023-12-31 01:49:52,642 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-444338-l2/gw2
2023-12-31 01:49:53,152 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-31 01:49:53,152 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 43.3%
2023-12-31 01:49:53,152 T0000: NOTICE ROOT_PATH: /repo
2023-12-31 01:49:53,152 T0000: NOTICE Python: 3.8.10
2023-12-31 01:49:53,152 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D2T1:4
2023-12-31 01:49:53,152 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-31 01:49:53,152 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-31-01-49-42 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-444338-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-444338-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-444338-l2 --noop --feature-group master
2023-12-31 01:49:53,763 T0000: DEBUG 'errors' not set in properties for V1 assuming 'default'
2023-12-31 01:49:53,763 T0000: DEBUG 'errors' not set in properties for V2 assuming 'default'
2023-12-31 01:49:53,763 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-31 01:49:53,763 T0000: WARN  Registering Topology
2023-12-31 01:49:53,783 T0000: INFO  Connecting all devices
2023-12-31 01:49:53,784 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8'] skip: False
2023-12-31 01:49:54,261 T0005: INFO  [D1-V1] Connecting to device (V1): sonic_ssh: 172.18.0.2:22 ..
2023-12-31 01:49:54,262 T0005: INFO  [D1-V1] TRY Authentication: 172.18.0.2:22 admin YourPaSsWoRd
2023-12-31 01:49:54,267 T0006: INFO  [D2-V2] Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2023-12-31 01:49:54,268 T0006: INFO  [D2-V2] TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2023-12-31 01:49:54,797 T0000: INFO  TG Scapy Init
2023-12-31 01:49:54,798 T0000: INFO  TG Base Init skip: False
2023-12-31 01:49:54,804 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-31 01:49:54,926 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_31_01_49_54_855534/gw2/default.log
2023-12-31 01:49:54,944 T0000: DEBUG REQ: tg_connect(port_list=['1/1', '1/2', '1/3', '1/4', '1/5', '1/6', '1/7', '1/8'])
2023-12-31 01:49:59,506 T0006: DEBUG [D2-V2] Connected ...
2023-12-31 01:49:59,514 T0005: DEBUG [D1-V1] Connected ...
2023-12-31 01:50:00,343 T0005: INFO  [D1-V1] Prompt at the connection start: 'admin@V1:~$' 
2023-12-31 01:50:00,347 T0005: AUDIT [D1-V1] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-31 01:50:00,350 T0006: INFO  [D2-V2] Prompt at the connection start: 'admin@V2:~$' 
2023-12-31 01:50:00,350 T0006: AUDIT [D2-V2] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-31 01:50:00,759 T0005: INFO  [D1-V1] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-31 01:50:00,765 T0006: INFO  [D2-V2] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-31 01:50:01,023 T0005: INFO  [D1-V1]  01:50:00 up 23 days,  2:53,  1 user,  load average: 60.76, 21.25, 11.54
2023-12-31 01:50:01,023 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:01,031 T0005: AUDIT [D1-V1] cat /proc/uptime
2023-12-31 01:50:01,034 T0006: INFO  [D2-V2]  01:50:00 up 23 days,  2:53,  1 user,  load average: 60.76, 21.25, 11.54
2023-12-31 01:50:01,035 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:01,037 T0006: AUDIT [D2-V2] cat /proc/uptime
2023-12-31 01:50:01,438 T0005: INFO  [D1-V1] FCMD: cat /proc/uptime
2023-12-31 01:50:01,443 T0006: INFO  [D2-V2] FCMD: cat /proc/uptime
2023-12-31 01:50:01,694 T0005: INFO  [D1-V1] 1997602.63 157474267.54
2023-12-31 01:50:01,694 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:01,697 T0005: INFO  [D1-V1] UPTIME: 1997602.63
2023-12-31 01:50:01,697 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:01,703 T0006: INFO  [D2-V2] 1997602.63 157474268.17
2023-12-31 01:50:01,703 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:01,706 T0006: INFO  [D2-V2] UPTIME: 1997602.63
2023-12-31 01:50:01,707 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:02,110 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:02,115 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:02,726 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:02,726 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:02,729 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:02,731 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:02,731 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:02,773 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:02,773 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:02,776 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:02,777 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:02,777 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:05,192 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/1": "port-1", "1/2": "port-2", "1/3": "port-3", "1/4": "port-4", "1/5": "port-5", "1/6": "port-6", "1/7": "port-7", "1/8": "port-8"}, "status": 1}
2023-12-31 01:50:05,208 T0000: INFO  TG Connection: Success
2023-12-31 01:50:05,208 T0000: INFO  TG Connect...done
2023-12-31 01:50:07,736 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:07,780 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:08,145 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:08,187 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:08,755 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:08,755 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:08,757 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:08,759 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:08,759 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:08,799 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:08,800 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:08,802 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:08,803 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:08,803 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:13,764 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:13,808 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:14,172 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:14,214 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:14,783 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:14,784 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:14,786 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:14,788 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:14,788 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:14,824 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:14,824 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:14,827 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:14,830 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:14,830 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:19,792 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:19,835 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:20,199 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:20,241 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:20,850 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:20,850 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:20,853 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:20,854 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:20,855 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:20,859 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:20,860 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:20,862 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:20,864 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:20,864 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:25,860 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:25,868 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:26,267 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:26,275 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:26,877 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:26,878 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:26,880 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:26,882 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:26,883 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:26,885 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:26,885 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:26,887 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:26,889 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:26,889 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:31,888 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:31,893 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:32,294 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:32,299 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:32,953 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:32,953 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:32,955 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:32,958 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:32,958 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:32,960 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:32,960 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:32,963 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:32,965 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:32,965 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:37,964 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:37,970 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:38,371 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:38,378 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:39,032 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:39,032 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:39,034 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:39,035 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:39,035 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:39,039 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:39,039 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:39,041 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:39,043 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:39,044 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:44,040 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:44,049 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:44,447 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:44,456 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:45,057 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:45,058 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:45,060 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:45,062 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:45,062 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:45,066 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:45,066 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:45,069 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:45,071 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:45,071 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:50,068 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:50,076 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:50,477 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:50,482 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:51,091 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:51,092 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:51,094 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:51,094 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:51,097 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:51,100 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:51,102 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:51,102 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:51,104 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:51,104 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:56,105 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:56,108 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:56,516 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:56,521 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:57,127 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:50:57,128 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:50:57,130 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:57,132 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:57,132 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:50:57,180 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:50:57,181 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:50:57,183 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:50:57,185 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:50:57,185 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:02,136 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:02,190 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:02,543 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:02,598 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:03,155 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:03,155 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:03,158 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:03,159 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:03,160 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:03,207 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:03,208 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:03,210 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:03,212 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:03,212 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:08,165 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:08,216 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:08,573 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:08,622 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:09,183 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:09,183 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:09,185 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:09,187 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:09,187 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:09,233 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:09,233 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:09,235 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:09,237 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:09,237 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:14,192 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:14,243 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:14,599 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:14,650 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:15,210 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:15,211 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:15,213 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:15,215 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:15,215 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:15,260 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:15,260 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:15,263 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:15,265 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:15,265 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:20,219 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:20,268 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:20,626 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:20,675 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:21,236 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:21,236 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:21,239 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:21,241 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:21,241 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:21,284 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:21,284 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:21,287 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:21,289 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:21,289 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:26,244 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:26,293 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:26,651 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:26,702 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:27,262 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:27,262 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:27,265 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:27,267 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:27,267 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:27,312 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:27,312 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:27,315 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:27,317 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:27,317 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:32,272 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:32,322 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:32,679 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:32,729 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:33,289 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:33,290 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:33,292 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:33,294 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:33,294 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:33,339 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:33,340 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:33,342 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:33,344 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:33,344 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:38,296 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:38,348 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:38,703 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:38,755 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:39,312 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:39,312 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:39,315 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:39,317 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:39,317 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:39,365 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:39,365 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:39,368 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:39,370 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:39,370 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:44,320 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:44,372 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:44,726 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:44,777 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:45,388 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:45,388 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:45,391 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:45,391 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:45,394 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:45,396 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:45,397 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:45,397 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:45,399 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:45,399 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:50,403 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:50,405 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:50,815 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:50,821 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:51,432 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:51,432 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:51,435 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:51,435 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:51,438 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:51,440 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:51,442 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:51,442 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:51,444 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:51,444 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:56,448 T0005: AUDIT [D1-V1] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:56,449 T0006: AUDIT [D2-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:56,863 T0005: INFO  [D1-V1] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:56,870 T0006: INFO  [D2-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:57,477 T0005: INFO  [D1-V1] Error response from daemon: No such container: bgp
2023-12-31 01:51:57,478 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:51:57,481 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:57,483 T0006: INFO  [D2-V2] Error response from daemon: No such container: bgp
2023-12-31 01:51:57,484 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:51:57,486 T0005: WARN  [D1-V1] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:57,486 T0005: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:51:57,488 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-31 01:51:57,490 T0006: WARN  [D2-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-31 01:51:57,490 T0006: INFO  Sleep for 5 sec(s)... @371
2023-12-31 01:52:02,493 T0005: ERROR [D1-V1] Failed to read hostname from vtysh - assuming sonic
2023-12-31 01:52:02,496 T0005: INFO  [D1-V1] Base Prompt: sonic
2023-12-31 01:52:02,498 T0006: ERROR [D2-V2] Failed to read hostname from vtysh - assuming sonic
2023-12-31 01:52:02,500 T0005: DEBUG [D1-V1] Wait for system ready Ref: 866
2023-12-31 01:52:02,503 T0006: INFO  [D2-V2] Base Prompt: sonic
2023-12-31 01:52:02,505 T0006: DEBUG [D2-V2] Wait for system ready Ref: 866
2023-12-31 01:52:02,909 T0005: INFO  [D1-V1] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-31 01:52:02,914 T0006: INFO  [D2-V2] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-31 01:52:03,170 T0005: INFO  [D1-V1] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-31 01:52:03,171 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:52:03,175 T0006: INFO  [D2-V2] md5sum: /etc/spytest/remote/spytest-helper.py: No such file or directory
2023-12-31 01:52:03,175 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:52:03,179 T0005: INFO  [D1-V1] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-31 01:52:03,180 T0006: INFO  [D2-V2] MD5 different SRC: 4522abaafb8e29890a8377a810228525 DST: []
2023-12-31 01:52:03,181 T0005: INFO  [D1-V1] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 01:52:03,182 T0006: INFO  [D2-V2] Trying to upload file '/repo/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 01:52:03,183 T0005: INFO  [D1-V1] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V1): /tmp/spytest-helper.py
2023-12-31 01:52:03,183 T0006: INFO  [D2-V2] Transfer: SRC(SVR/VDI): /repo/spytest/remote/spytest-helper.py DST(V2): /tmp/spytest-helper.py
2023-12-31 01:52:03,184 T0005: ERROR [D1-V1] No mgmt IP
2023-12-31 01:52:03,185 T0006: ERROR [D2-V2] No mgmt IP
2023-12-31 01:52:03,185 T0005: INFO  [D1-V1] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-31 01:52:03,186 T0006: INFO  [D2-V2] Doing SFTP transfer IP = None/YourPaSsWoRd/broadcom
2023-12-31 01:52:03,354 T0006: INFO  [D2-V2] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-31 01:52:03,372 T0005: INFO  [D1-V1] FCMD: sudo md5sum /tmp/spytest-helper.py
2023-12-31 01:52:03,612 T0006: INFO  [D2-V2] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-31 01:52:03,612 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:52:03,615 T0006: INFO  [D2-V2] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 01:52:03,616 T0006: INFO  [D2-V2] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-31 01:52:03,628 T0005: INFO  [D1-V1] 4522abaafb8e29890a8377a810228525  /tmp/spytest-helper.py
2023-12-31 01:52:03,629 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:52:03,632 T0005: INFO  [D1-V1] Trying to copy file to '/etc/spytest/remote/spytest-helper.py'. attempt '1'
2023-12-31 01:52:03,634 T0005: INFO  [D1-V1] SCMD: sudo mkdir -p /etc/spytest/remote && sudo cp -f /tmp/spytest-helper.py /etc/spytest/remote/spytest-helper.py
2023-12-31 01:52:06,224 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:52:06,226 T0006: WARN  [D2-V2] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-31 01:52:06,227 T0006: INFO  [D2-V2] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:52:06,241 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:52:06,243 T0005: WARN  [D1-V1] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-31 01:52:06,245 T0005: INFO  [D1-V1] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:52:10,055 T0006: WARN  [D2-V2] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:52:10,056 T0006: INFO  [D2-V2] 
2023-12-31 01:52:10,056 T0006: INFO  [D2-V2] Remote CMD: 'show platform summary'
2023-12-31 01:52:10,056 T0006: INFO  [D2-V2] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 01:52:10,056 T0006: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 01:52:10,056 T0006: INFO  [D2-V2]     from show.main import cli
2023-12-31 01:52:10,056 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 01:52:10,056 T0006: INFO  [D2-V2]     if is_gearbox_configured():
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2] 
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2] Remote CMD: 'sudo show interfaces status '
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 01:52:10,057 T0006: INFO  [D2-V2]     from show.main import cli
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]     if is_gearbox_configured():
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]     app_db.connect(app_db.APPL_DB)
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2] 
2023-12-31 01:52:10,058 T0006: INFO  [D2-V2] admin@V2:~$ 
2023-12-31 01:52:10,059 T0006: ERROR [D2-V2] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:52:10,075 T0005: WARN  [D1-V1] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:52:10,076 T0005: INFO  [D1-V1] 
2023-12-31 01:52:10,076 T0005: INFO  [D1-V1] Remote CMD: 'show platform summary'
2023-12-31 01:52:10,076 T0005: INFO  [D1-V1] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 01:52:10,076 T0005: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 01:52:10,076 T0005: INFO  [D1-V1]     from show.main import cli
2023-12-31 01:52:10,076 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 01:52:10,076 T0005: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1] 
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1] Remote CMD: 'sudo show interfaces status '
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]   File "/usr/local/bin/show", line 5, in <module>
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]     from show.main import cli
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-31 01:52:10,077 T0005: INFO  [D1-V1]     if is_gearbox_configured():
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1]     app_db.connect(app_db.APPL_DB)
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1] 
2023-12-31 01:52:10,078 T0005: INFO  [D1-V1] admin@V1:~$ 
2023-12-31 01:52:10,078 T0005: ERROR [D1-V1] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-31 01:52:10,079 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-31 01:52:10,079 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-31 01:52:10,080 T0004: ERROR [D1-V1] Failed to connect to device
2023-12-31 01:52:10,082 T0004: ERROR [D2-V2] Failed to connect to device
2023-12-31 01:52:10,082 T0000: ERROR Failed to connect (['V1', 'V2'])
2023-12-31 01:52:10,082 T0000: INFO  --FINISH--RUN--4 @559
