ordering items took 0:00:01
Tests considered 72 and ignored 317
2024-01-08 00:48:26,950 T0000: NOTICE WORKER = gw3
2024-01-08 00:48:26,950 T0000: NOTICE using testbed file /data/work/logs/docker-master-449712-l3/testbed_1_2_2.yaml
2024-01-08 00:48:26,950 T0000: NOTICE Execution Start Time: 2024-01-08 00:48:26.948096
2024-01-08 00:48:26,951 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-449712-l3/gw3
2024-01-08 00:48:27,443 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2024-01-08 00:48:27,443 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 56.5%
2024-01-08 00:48:27,443 T0000: NOTICE ROOT_PATH: /repo
2024-01-08 00:48:27,443 T0000: NOTICE Python: 3.8.10
2024-01-08 00:48:27,443 T0000: NOTICE Topology unknown: D1T1:4,D1D2:6,D2T1:4
2024-01-08 00:48:27,443 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2024-01-08 00:48:27,443 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2024-01-08-00-45-56 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-449712-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-449712-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-449712-l3 --noop --feature-group master
2024-01-08 00:48:28,070 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2024-01-08 00:48:28,070 T0000: DEBUG 'errors' not set in properties for V4 assuming 'default'
2024-01-08 00:48:28,070 T0000: INFO  TGEN-IP 127.0.0.1
2024-01-08 00:48:28,071 T0000: WARN  Registering Topology
2024-01-08 00:48:28,092 T0000: INFO  Connecting all devices
2024-01-08 00:48:28,093 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'] skip: False
2024-01-08 00:48:28,585 T0005: INFO  [D1-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2024-01-08 00:48:28,586 T0005: INFO  [D1-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2024-01-08 00:48:28,590 T0006: INFO  [D2-V4] Connecting to device (V4): sonic_ssh: 172.18.0.5:22 ..
2024-01-08 00:48:28,591 T0006: INFO  [D2-V4] TRY Authentication: 172.18.0.5:22 admin YourPaSsWoRd
2024-01-08 00:48:29,112 T0000: INFO  TG Scapy Init
2024-01-08 00:48:29,112 T0000: INFO  TG Base Init skip: False
2024-01-08 00:48:29,122 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2024-01-08 00:48:29,307 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2024_01_08_00_48_29_149199/gw3/default.log
2024-01-08 00:48:29,335 T0000: DEBUG REQ: tg_connect(port_list=['1/9', '1/10', '1/11', '1/12', '1/13', '1/14', '1/15', '1/16'])
2024-01-08 00:48:33,796 T0006: DEBUG [D2-V4] Connected ...
2024-01-08 00:48:33,801 T0005: DEBUG [D1-V3] Connected ...
2024-01-08 00:48:34,630 T0006: INFO  [D2-V4] Prompt at the connection start: 'admin@V4:~$' 
2024-01-08 00:48:34,634 T0006: AUDIT [D2-V4] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-08 00:48:34,637 T0005: INFO  [D1-V3] Prompt at the connection start: 'admin@V3:~$' 
2024-01-08 00:48:34,638 T0005: AUDIT [D1-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-08 00:48:35,047 T0006: INFO  [D2-V4] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-08 00:48:35,049 T0005: INFO  [D1-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-08 00:48:35,309 T0006: INFO  [D2-V4]  00:48:35 up 31 days,  1:54,  1 user,  load average: 6.35, 14.63, 11.41
2024-01-08 00:48:35,309 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:48:35,321 T0006: AUDIT [D2-V4] cat /proc/uptime
2024-01-08 00:48:35,324 T0005: INFO  [D1-V3]  00:48:35 up 31 days,  1:54,  1 user,  load average: 6.35, 14.63, 11.41
2024-01-08 00:48:35,324 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:48:35,326 T0005: AUDIT [D1-V3] cat /proc/uptime
2024-01-08 00:48:35,727 T0006: INFO  [D2-V4] FCMD: cat /proc/uptime
2024-01-08 00:48:35,732 T0005: INFO  [D1-V3] FCMD: cat /proc/uptime
2024-01-08 00:48:35,984 T0006: INFO  [D2-V4] 2685280.81 211625060.60
2024-01-08 00:48:35,985 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:48:35,988 T0006: INFO  [D2-V4] UPTIME: 2685280.81
2024-01-08 00:48:35,989 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:35,993 T0005: INFO  [D1-V3] 2685280.82 211625061.07
2024-01-08 00:48:35,994 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:48:35,996 T0005: INFO  [D1-V3] UPTIME: 2685280.82
2024-01-08 00:48:35,997 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:36,401 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:36,407 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:37,017 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:48:37,017 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:48:37,020 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:48:37,021 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:48:37,024 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:37,027 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:37,029 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:37,029 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:48:37,030 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:37,030 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:48:41,927 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12", "1/13": "port-13", "1/14": "port-14", "1/15": "port-15", "1/16": "port-16"}, "status": 1}
2024-01-08 00:48:41,941 T0000: INFO  TG Connection: Success
2024-01-08 00:48:41,941 T0000: INFO  TG Connect...done
2024-01-08 00:48:42,033 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:42,034 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:42,446 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:42,451 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:43,057 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:48:43,057 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:48:43,060 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:43,063 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:48:43,063 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:48:43,066 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:43,066 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:48:43,068 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:43,070 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:43,070 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:48:48,070 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:48,074 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:48,476 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:48,481 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:49,085 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:48:49,085 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:48:49,088 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:49,090 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:49,090 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:48:49,092 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:48:49,093 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:48:49,095 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:49,097 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:49,097 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:48:54,096 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:54,102 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:54,503 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:54,509 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:55,112 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:48:55,113 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:48:55,115 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:55,116 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:55,116 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:48:55,118 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:48:55,119 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:48:55,120 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:48:55,120 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:48:55,120 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:00,122 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:00,123 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:00,537 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:00,543 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:01,155 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:01,155 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:01,158 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:01,159 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:01,160 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:01,204 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:01,205 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:01,207 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:01,208 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:01,208 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:06,165 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:06,214 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:06,573 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:06,621 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:07,182 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:07,182 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:07,185 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:07,187 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:07,187 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:07,233 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:07,234 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:07,237 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:07,240 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:07,240 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:12,193 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:12,246 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:12,600 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:12,653 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:13,211 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:13,212 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:13,214 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:13,216 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:13,216 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:13,313 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:13,313 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:13,315 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:13,317 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:13,317 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:18,218 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:18,322 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:18,626 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:18,733 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:19,287 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:19,287 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:19,290 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:19,292 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:19,292 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:19,345 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:19,345 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:19,348 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:19,350 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:19,350 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:24,298 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:24,354 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:24,705 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:24,761 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:25,315 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:25,315 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:25,318 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:25,320 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:25,320 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:25,369 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:25,370 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:25,372 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:25,374 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:25,374 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:30,322 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:30,378 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:30,729 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:30,785 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:31,440 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:31,440 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:31,443 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:31,445 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:31,445 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:31,448 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:31,448 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:31,450 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:31,451 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:31,451 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:36,451 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:36,457 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:36,858 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:36,863 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:37,469 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:37,469 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:37,472 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:37,474 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:37,475 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:37,477 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:37,477 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:37,479 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:37,481 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:37,481 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:42,483 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:42,487 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:42,890 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:42,897 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:43,507 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:43,507 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:43,510 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:43,510 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:43,513 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:43,515 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:43,517 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:43,518 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:43,519 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:43,520 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:48,523 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:48,523 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:48,936 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:48,942 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:49,552 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:49,553 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:49,555 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:49,557 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:49,557 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:49,602 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:49,602 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:49,605 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:49,606 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:49,606 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:54,558 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:54,610 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:54,965 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:55,017 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:55,576 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:49:55,576 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:49:55,579 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:55,581 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:55,582 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:49:55,627 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:49:55,627 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:49:55,630 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:49:55,632 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:49:55,632 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:00,586 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:00,634 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:00,993 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:01,045 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:01,602 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:50:01,603 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:01,605 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:01,607 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:01,607 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:01,654 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:50:01,655 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:01,657 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:01,659 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:01,659 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:06,610 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:06,665 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:07,016 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:07,073 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:07,625 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:50:07,625 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:07,628 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:07,629 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:07,630 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:07,683 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:50:07,683 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:07,686 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:07,688 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:07,688 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:12,635 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:12,690 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:13,043 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:13,097 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:13,653 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:50:13,653 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:13,657 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:13,659 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:13,659 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:13,758 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:50:13,758 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:13,760 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:13,761 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:13,762 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:18,662 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:18,768 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:19,072 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:19,175 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:19,836 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:50:19,836 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:19,837 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:19,837 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:19,837 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:19,990 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:50:19,990 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:19,994 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:19,997 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:19,997 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:24,843 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:25,003 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:25,252 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:25,410 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:25,962 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:50:25,962 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:25,965 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:25,967 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:25,967 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:26,119 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:50:26,119 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:26,121 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:26,122 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:26,123 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:30,973 T0006: AUDIT [D2-V4] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:31,128 T0005: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:31,382 T0006: INFO  [D2-V4] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:31,535 T0005: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:32,043 T0006: INFO  [D2-V4] Error response from daemon: No such container: bgp
2024-01-08 00:50:32,043 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:32,046 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:32,047 T0006: WARN  [D2-V4] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:32,047 T0006: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:32,197 T0005: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 00:50:32,197 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:32,200 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 00:50:32,201 T0005: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 00:50:32,201 T0005: INFO  Sleep for 5 sec(s)... @371
2024-01-08 00:50:37,051 T0006: ERROR [D2-V4] Failed to read hostname from vtysh - assuming sonic
2024-01-08 00:50:37,054 T0006: INFO  [D2-V4] Base Prompt: sonic
2024-01-08 00:50:37,055 T0006: DEBUG [D2-V4] Wait for system ready Ref: 866
2024-01-08 00:50:37,208 T0005: ERROR [D1-V3] Failed to read hostname from vtysh - assuming sonic
2024-01-08 00:50:37,210 T0005: INFO  [D1-V3] Base Prompt: sonic
2024-01-08 00:50:37,211 T0005: DEBUG [D1-V3] Wait for system ready Ref: 866
2024-01-08 00:50:37,461 T0006: INFO  [D2-V4] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-08 00:50:37,620 T0005: INFO  [D1-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-08 00:50:37,719 T0006: INFO  [D2-V4] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2024-01-08 00:50:37,719 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:37,727 T0006: WARN  [D2-V4] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-08 00:50:37,728 T0006: INFO  [D2-V4] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 00:50:37,882 T0005: INFO  [D1-V3] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2024-01-08 00:50:37,882 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:37,887 T0005: WARN  [D1-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-08 00:50:37,888 T0005: INFO  [D1-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 00:50:41,560 T0006: WARN  [D2-V4] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 00:50:41,561 T0006: INFO  [D2-V4] 
2024-01-08 00:50:41,561 T0006: INFO  [D2-V4] Remote CMD: 'show platform summary'
2024-01-08 00:50:41,561 T0006: INFO  [D2-V4] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 00:50:41,562 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 00:50:41,562 T0006: INFO  [D2-V4]     from show.main import cli
2024-01-08 00:50:41,562 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 00:50:41,562 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2024-01-08 00:50:41,562 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,562 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 00:50:41,562 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2024-01-08 00:50:41,563 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 00:50:41,563 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 00:50:41,563 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,563 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 00:50:41,563 T0006: INFO  [D2-V4] 
2024-01-08 00:50:41,563 T0006: INFO  [D2-V4] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-08 00:50:41,563 T0006: INFO  [D2-V4] Remote CMD: 'sudo show interfaces status '
2024-01-08 00:50:41,564 T0006: INFO  [D2-V4] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 00:50:41,564 T0006: INFO  [D2-V4]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 00:50:41,564 T0006: INFO  [D2-V4]     from show.main import cli
2024-01-08 00:50:41,564 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 00:50:41,564 T0006: INFO  [D2-V4]     if is_gearbox_configured():
2024-01-08 00:50:41,564 T0006: INFO  [D2-V4]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,564 T0006: INFO  [D2-V4]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 00:50:41,565 T0006: INFO  [D2-V4]     app_db.connect(app_db.APPL_DB)
2024-01-08 00:50:41,565 T0006: INFO  [D2-V4]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 00:50:41,565 T0006: INFO  [D2-V4]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 00:50:41,565 T0006: INFO  [D2-V4]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,565 T0006: INFO  [D2-V4] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 00:50:41,565 T0006: INFO  [D2-V4] 
2024-01-08 00:50:41,565 T0006: INFO  [D2-V4] admin@V4:~$ 
2024-01-08 00:50:41,566 T0006: ERROR [D2-V4] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 00:50:41,711 T0005: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 00:50:41,713 T0005: INFO  [D1-V3] 
2024-01-08 00:50:41,713 T0005: INFO  [D1-V3] Remote CMD: 'show platform summary'
2024-01-08 00:50:41,713 T0005: INFO  [D1-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]     from show.main import cli
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 00:50:41,714 T0005: INFO  [D1-V3] 
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3] Remote CMD: 'sudo show interfaces status '
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3]     from show.main import cli
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3]     if is_gearbox_configured():
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,715 T0005: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 00:50:41,716 T0005: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2024-01-08 00:50:41,716 T0005: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 00:50:41,716 T0005: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 00:50:41,716 T0005: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 00:50:41,716 T0005: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 00:50:41,716 T0005: INFO  [D1-V3] 
2024-01-08 00:50:41,716 T0005: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 00:50:41,717 T0005: ERROR [D1-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 00:50:41,718 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-08 00:50:41,718 T0004: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-08 00:50:41,719 T0004: ERROR [D1-V3] Failed to connect to device
2024-01-08 00:50:41,720 T0004: ERROR [D2-V4] Failed to connect to device
2024-01-08 00:50:41,721 T0000: ERROR Failed to connect (['V3', 'V4'])
2024-01-08 00:50:41,721 T0000: INFO  --FINISH--RUN--4 @559
