2024-01-04 00:59:58,003 T0002: INFO  Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2024-01-04 00:59:58,004 T0002: INFO  TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2024-01-04 01:00:03,273 T0002: DEBUG Connected ...
2024-01-04 01:00:04,090 T0002: INFO  Prompt at the connection start: 'admin@V2:~$' 
2024-01-04 01:00:04,500 T0002: INFO  FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-04 01:00:04,759 T0002: INFO   01:00:04 up 27 days,  2:04,  1 user,  load average: 13.02, 14.67, 11.75
2024-01-04 01:00:04,759 T0002: INFO  admin@V2:~$ 
2024-01-04 01:00:05,750 T0002: INFO  FCMD: cat /proc/uptime
2024-01-04 01:00:06,218 T0000: INFO  
2024-01-04 01:00:06,218 T0000: INFO  ================== batch/test_spytest_infra_1.py::test_spytest_infra_first ==================
2024-01-04 01:00:06,226 T0000: INFO  Report():batch/test_spytest_infra_1.py::test_spytest_infra_first 0:00:00 module configuration failed.  @5445
2024-01-04 01:00:06,360 T0002: INFO  2340286.34 184498447.06
2024-01-04 01:00:06,360 T0002: INFO  admin@V2:~$ 
2024-01-04 01:00:06,362 T0002: INFO  UPTIME: 2340286.34
2024-01-04 01:00:06,769 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-04 01:00:07,430 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-04 01:00:07,430 T0002: INFO  admin@V2:~$ 
2024-01-04 01:00:07,433 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-04 01:00:07,435 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
