#,Node,Feature,TestCase,Result,ResultType,ExecutedOn,Description,Function,Module,Devices,KnownIssue
1,gw3,Regression,ft_add_unknownvlan_interface,Pass,Mapped,2024-01-08 01:00:42,Test case passed,test_ft_add_unknownvlan_interface,switching/test_vlan.py,"V3, V4",
2,gw3,Regression,ft_vlan_delete_with_member,Pass,Mapped,2024-01-08 01:00:56,Test case passed,test_ft_vlan_delete_with_member,switching/test_vlan.py,"V3, V4",
3,gw2,Regression,FtOpSoSwLagFn042,Pass,Mapped,2024-01-08 01:01:28,Test case passed,test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
4,gw2,Regression,FtOpSoSwLagFn041,Pass,Mapped,2024-01-08 01:01:28,Test case passed,test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
5,gw2,PortChannel Config Enhancements,FtOpSoSwPominFn007,Pass,Mapped,2024-01-08 01:01:52,Test case passed,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,switching/test_portchannel.py,"V1, V2",
6,gw3,Regression,ft_vlan_trunk_tagged,Pass,Mapped,2024-01-08 01:02:23,Test case passed,test_ft_vlan_trunk_tagged,switching/test_vlan.py,"V3, V4",
7,gw3,Regression,ft_show_vlan_brief,Pass,Mapped,2024-01-08 01:02:23,Test case passed,test_ft_vlan_trunk_tagged,switching/test_vlan.py,"V3, V4",
8,gw2,Regression,ft_ssh_service_disable,Pass,Mapped,2024-01-08 01:08:25,Test case passed,test_ft_ssh_service_disable,system/test_ssh.py,"V1, V2",
9,gw3,warmboot,ft_reboot_fdb_fast_reboot,ScriptError,Mapped,2024-01-08 01:14:55,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
10,gw3,warmboot,ft_max_vlan_save_reload,ScriptError,Mapped,2024-01-08 01:14:55,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
11,gw3,warmboot,FtOpSoSysFRFn005,ScriptError,Mapped,2024-01-08 01:14:55,Exception TypeError 'NoneType' object is not subscriptable in file /apis/system/basic.py at line 1389,test_ft_vlan_save_config_warm_and_fast_reboot,switching/test_vlan.py,"V3, V4",
12,gw2,Regression,ft_ssh_add_user_verify,Fail,Mapped,2024-01-08 01:19:33,Test case Failed.,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
13,gw2,Control Plane ACL,test_ft_controlplane_acl_service_sshv4,Pass,SubTest,2024-01-08 01:19:33,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
14,gw2,Control Plane ACL,test_ft_controlplane_acl_service_sshv6,Pass,SubTest,2024-01-08 01:19:33,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
15,gw2,Control Plane ACL,test_ft_controlplane_acl_service_snmp,Fail,SubTest,2024-01-08 01:19:33,SNMP output is not found after walk of with control plane ACL service SNMP after reboot OID,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
16,gw2,Regression,CETA_SONIC_67575,Pass,Mapped,2024-01-08 01:19:55,Test case passed,test_ft_verify_logs_at_the_time_of_ssh_login_success,system/test_ssh.py,"V1, V2",
17,gw3,Regression,FtOpSoSyInIpFn002,DUTFail,Mapped,2024-01-08 01:22:18,Error response from daemon: Container is not running,test_ft_port_fn_verify_shut_noshut,system/test_interface.py,"V3, V4",
18,gw2,Regression,ft_lldp_LocManAddrLen,Fail,Mapped,2024-01-08 01:27:22,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrLen,system/test_lldp.py,"V1, V2",
19,gw2,Regression,ft_lldp_LocManAddrlfld,Fail,Mapped,2024-01-08 01:27:22,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrlfld,system/test_lldp.py,"V1, V2",
20,gw2,Regression,ft_lldp_LocManAddrEntry,Fail,Mapped,2024-01-08 01:27:23,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_LocManAddrEntry,system/test_lldp.py,"V1, V2",
21,gw2,Regression,ft_lldp_ConfigManAddrEntry,Fail,Mapped,2024-01-08 01:27:23,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_ConfigManAddrEntry,system/test_lldp.py,"V1, V2",
22,gw2,Regression,ft_lldp_lldplocportid,Fail,Mapped,2024-01-08 01:27:23,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocportid,system/test_lldp.py,"V1, V2",
23,gw2,Regression,ft_lldp_lldplocsysname,Fail,Mapped,2024-01-08 01:27:24,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysname,system/test_lldp.py,"V1, V2",
24,gw2,Regression,ft_lldp_lldplocsysdesc,Fail,Mapped,2024-01-08 01:27:24,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_lldplocsysdesc,system/test_lldp.py,"V1, V2",
25,gw2,SNMP Agent Optimization,ft_snmp_lldp_prem_manaddr_table,Fail,Mapped,2024-01-08 01:27:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_rem_man_addr_table,system/test_lldp.py,"V1, V2",
26,gw2,Regression,FtOpSoSwlldpFn011,Fail,Mapped,2024-01-08 01:27:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
27,gw2,Regression,FtOpSoSwlldpFn010,Fail,Mapped,2024-01-08 01:27:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
28,gw2,Regression,FtOpSoSwlldpFn009,Fail,Mapped,2024-01-08 01:27:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
29,gw2,Regression,FtOpSoSwlldpFn008,Fail,Mapped,2024-01-08 01:27:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
30,gw2,Regression,FtOpSoSwlldpFn004,Fail,Mapped,2024-01-08 01:27:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_non_default_config,system/test_lldp.py,"V1, V2",
31,gw2,Regression,FtOpSoSwlldpFn013,Fail,Mapped,2024-01-08 01:27:25,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_docker_restart,system/test_lldp.py,"V1, V2",
32,gw2,Regression,lldp_verify_counters,Fail,Mapped,2024-01-08 01:27:26,module configuration failed. LLDP neighbors information is not found after polling @5445,test_lldp_verify_counters,system/test_lldp.py,"V1, V2",
33,gw2,Regression,ft_lldp_with_remote_server,Fail,Mapped,2024-01-08 01:27:26,module configuration failed. LLDP neighbors information is not found after polling @5445,test_ft_lldp_with_remote_server,system/test_lldp.py,"V1, V2",
34,gw7,Regression,ft_tacacsauth_enable_pamfile_created,Fail,Mapped,2024-01-08 01:31:00,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V3,
35,gw7,Regression,ft_tacacs_ssh_login,Fail,Mapped,2024-01-08 01:31:00,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V3,
36,gw7,Regression,ft_tacacs_single_server_for_auth,Fail,Mapped,2024-01-08 01:31:00,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V3,
37,gw7,Regression,ft_tacacs_default_login,Fail,Mapped,2024-01-08 01:31:00,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V3,
38,gw7,Regression,executing_server_key_in_appropriate_mode,Fail,Mapped,2024-01-08 01:31:00,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V3,
39,gw7,Regression,auth_shared_keys ,Fail,Mapped,2024-01-08 01:31:00,PAM file is not created,test_ft_tacacs_ssh_login_with_tacacs_operations,security/test_tacacs.py,V3,
40,gw4,Instrumentation,ft_sf_wm_telemetry_interval,Pass,Mapped,2024-01-08 01:31:26,verification of configured telemetry interval and reset to default interval is successful,test_ft_watermark_telemetry_interval,system/test_snapshot.py,V4,
41,gw4,Instrumentation Enhancements,ft_sf_snapshot_tam_Error_Logs,Fail,SubTest,2024-01-08 01:31:26,Error logs are getting generated on the device,test_ft_watermark_telemetry_interval,system/test_snapshot.py,V4,
42,gw7,Regression,ft_snmp_sysName,Fail,Mapped,2024-01-08 01:38:32,sysname output is not in sync between system and snmp,test_ft_snmp_sysName,system/test_snmp.py,V3,
43,gw7,Regression,ft_snmp_test_syUpTime,Pass,Mapped,2024-01-08 01:38:38,Test case passed,test_ft_snmp_test_syUpTime,system/test_snmp.py,V3,
44,gw7,Regression,ft_snmp_sysDescr,Pass,Mapped,2024-01-08 01:38:46,Test case passed,test_ft_snmp_sysDescr,system/test_snmp.py,V3,
45,gw7,Regression,FtOpSoSySnFn008,Pass,Mapped,2024-01-08 01:38:53,Test case passed,test_ft_snmp_mib_2,system/test_snmp.py,V3,
46,gw7,Regression,FtOpSoSySnFn009,Pass,Mapped,2024-01-08 01:38:58,Test case passed,test_ft_snmp_if_mib_all,system/test_snmp.py,V3,
47,gw7,Regression,FtOpSoSySnFn010,Pass,Mapped,2024-01-08 01:39:03,Test case passed,test_ft_snmp_entity_mib_all,system/test_snmp.py,V3,
48,gw7,Regression,FtOpSoSySnFn013,Pass,Mapped,2024-01-08 01:39:08,Test case passed,test_ft_snmp_dot1q_dot1db_mib,system/test_snmp.py,V3,
49,gw7,Regression,FtOpSoSySnFn012,Pass,Mapped,2024-01-08 01:39:08,Test case passed,test_ft_snmp_dot1q_dot1db_mib,system/test_snmp.py,V3,
50,gw7,Regression,FtOpSoSySnFn015,Pass,Mapped,2024-01-08 01:39:17,Test case passed,test_ft_snmp_root_node_walk,system/test_snmp.py,V3,
51,gw7,Regression,FtOpSoSySnFn016,Pass,Mapped,2024-01-08 01:39:28,Test case passed,test_ft_snmp_ipAddressRowStatus_ipv6,system/test_snmp.py,V3,
52,gw7,Regression,FtOpSoSySnFn017,Pass,Mapped,2024-01-08 01:39:33,Test case passed,test_ft_snmp_ipAddressStorageType_ipv6,system/test_snmp.py,V3,
53,gw7,Regression,FtOpSoSySnFn020,Pass,Mapped,2024-01-08 01:39:38,Test case passed,test_ft_snmp_ipv6_If_Forward_default_HopLimit,system/test_snmp.py,V3,
54,gw7,Regression,FtOpSoSySnFn021,Pass,Mapped,2024-01-08 01:39:43,Test case passed,test_ft_snmp_ipv6scope_index_table,system/test_snmp.py,V3,
55,gw7,Regression,test_snmp_ip_forward_table,Pass,Mapped,2024-01-08 01:39:50,Test case passed,test_ft_snmp_ip_forward_table,system/test_snmp.py,V3,
56,gw7,SNMP Agent Optimization,ft_snmp_ifXTable,Pass,Mapped,2024-01-08 01:39:56,Test case passed,test_ft_snmp_ifx_table,system/test_snmp.py,V3,
57,gw7,SNMP Agent Optimization,ft_snmp_ip_System_Stats_Table,Pass,Mapped,2024-01-08 01:40:01,Test case passed,test_ft_snmp_ip_System_Stats_Table,system/test_snmp.py,V3,
58,gw7,SNMP Agent Optimization,ft_snmp_ip_IfStats_Table,Pass,Mapped,2024-01-08 01:40:06,Test case passed,test_ft_snmp_ip_IfStats_Table,system/test_snmp.py,V3,
59,gw7,SNMP Agent Optimization,ft_snmp_ip_Address_Table,Pass,Mapped,2024-01-08 01:40:11,Test case passed,test_ft_snmp_ip_Address_Table,system/test_snmp.py,V3,
60,gw7,SNMP Agent Optimization,ft_snmp_ip_NetToPhysical_Table,Pass,Mapped,2024-01-08 01:40:16,Test case passed,test_ft_snmp_ip_NetToPhysical_Table,system/test_snmp.py,V3,
61,gw7,SNMP Agent Optimization,ft_snmp_icmp_Msgs,Pass,Mapped,2024-01-08 01:40:21,Test case passed,test_ft_snmp_icmp_Msgs,system/test_snmp.py,V3,
62,gw7,SNMP Agent Optimization,ft_snmp_tcp_mib,Pass,Mapped,2024-01-08 01:40:28,Test case passed,test_ft_snmp_tcp_mib,system/test_snmp.py,V3,
63,gw7,SNMP Agent Optimization,ft_snmp_udp_mib,Pass,Mapped,2024-01-08 01:40:33,Test case passed,test_ft_snmp_udp_mib,system/test_snmp.py,V3,
64,gw7,SNMP Agent Optimization,ft_snmp_snmpv2_mib,Pass,Mapped,2024-01-08 01:40:38,Test case passed,test_ft_snmp_snmpv2_mib,system/test_snmp.py,V3,
65,gw7,SNMP Agent Optimization,ft_snmp_host_resource_mib,Pass,Mapped,2024-01-08 01:40:43,Test case passed,test_ft_snmp_host_resource_mib,system/test_snmp.py,V3,
66,gw7,SNMP Agent Optimization,ft_snmp_framework_mib,Pass,Mapped,2024-01-08 01:40:48,Test case passed,test_ft_snmp_framework_mib,system/test_snmp.py,V3,
67,gw7,SNMP Agent Optimization,ft_snmp_mpd_mib,Pass,Mapped,2024-01-08 01:40:53,Test case passed,test_ft_snmp_mpd_mib,system/test_snmp.py,V3,
68,gw7,SNMP Agent Optimization,ft_snmp_target_mib,Pass,Mapped,2024-01-08 01:40:58,Test case passed,test_ft_snmp_target_mib,system/test_snmp.py,V3,
69,gw7,SNMP Agent Optimization,ft_snmp_notification_mib,Pass,Mapped,2024-01-08 01:41:03,Test case passed,test_ft_snmp_notification_mib,system/test_snmp.py,V3,
70,gw7,SNMP Agent Optimization,ft_snmp_user_based_sm_mib,Pass,Mapped,2024-01-08 01:41:08,Test case passed,test_ft_snmp_user_based_sm_mib,system/test_snmp.py,V3,
71,gw7,SNMP Agent Optimization,ft_snmp_view_based_acm_mib,Pass,Mapped,2024-01-08 01:41:13,Test case passed,test_ft_snmp_view_based_acm_mib,system/test_snmp.py,V3,
72,gw7,SNMP Agent Optimization,ft_snmp_ent_physical_table,Pass,Mapped,2024-01-08 01:41:18,Test case passed,test_ft_snmp_ent_physical_table,system/test_snmp.py,V3,
73,gw7,SNMP Agent Optimization,ft_snmp_dot3_stats_table,Pass,Mapped,2024-01-08 01:41:23,Test case passed,test_ft_snmp_dot3_stats_table,system/test_snmp.py,V3,
74,gw7,SNMP Agent Optimization,ft_net_snmp_agent_mib,Pass,Mapped,2024-01-08 01:41:28,Test case passed,test_ft_net_snmp_agent_mib,system/test_snmp.py,V3,
75,gw7,SNMP Agent Optimization,ft_net_snmp_vacm_mib,Pass,Mapped,2024-01-08 01:41:33,Test case passed,test_ft_net_snmp_vacm_mib,system/test_snmp.py,V3,
76,gw7,SNMP Agent Optimization,ft_snmp_ucd_diskio_mib,Pass,Mapped,2024-01-08 01:41:38,Test case passed,test_ft_snmp_ucd_diskio_mib,system/test_snmp.py,V3,
77,gw7,SNMP Agent Optimization,ft_snmp_ucd_la_table,Pass,Mapped,2024-01-08 01:41:43,Test case passed,test_ft_snmp_ucd_la_table,system/test_snmp.py,V3,
78,gw7,SNMP Agent Optimization,ft_snmp_ucd_system_stats,Pass,Mapped,2024-01-08 01:41:48,Test case passed,test_ft_snmp_ucd_system_stats,system/test_snmp.py,V3,
79,gw7,SNMP MIB and Traps,SNMPQBr003,Fail,Mapped,2024-01-08 01:41:55,SNMP output is not found after walk of dot1qTpFdbPort OID,test_ft_snmp_dot1q_tp_fdb_port,system/test_snmp.py,V3,
80,gw7,SNMP MIB and Traps,SNMPQBr002,Pass,Mapped,2024-01-08 01:42:00,Test case passed,test_ft_snmp_dot1q_tp_fdb_address,system/test_snmp.py,V3,
81,gw4,Regression,ft_ntp_message_log_display_with_correct_time,ScriptError,Mapped,2024-01-08 01:42:19,Exception IndexError list index out of range in file /apis/system/ntp.py at line 347,test_ft_ntp_disable_enable_with_message_log,system/test_ntp.py,V4,
82,gw4,Regression,ft_ntp_disable_ntp_enable_ntp,ScriptError,Mapped,2024-01-08 01:42:19,Exception IndexError list index out of range in file /apis/system/ntp.py at line 347,test_ft_ntp_disable_enable_with_message_log,system/test_ntp.py,V4,
83,gw7,In-Memory Debug Log,FtOpSoSysImLogFn012,EnvFail,Mapped,2024-01-08 01:42:20,Test case Failed Couldn't get the snmptrapd process details from snmp trap server. Please check the snmp trap server process in the server.,test_ft_snmp_coldstart_trap,system/test_snmp.py,V3,
84,gw7,SNMP MIB and Traps,SNMPTrap004,EnvFail,Mapped,2024-01-08 01:42:20,Test case Failed Couldn't get the snmptrapd process details from snmp trap server. Please check the snmp trap server process in the server.,test_ft_snmp_coldstart_trap,system/test_snmp.py,V3,
85,gw4,Regression,ft_ntp_existsconfig,Pass,Mapped,2024-01-08 01:42:33,Test case passed,test_ntp_exists_config,system/test_ntp.py,V4,
86,gw7,Regression,FtOpSoSySnFn023,Fail,Mapped,2024-01-08 01:42:38,SNMP service is not up,test_ft_snmp_docker_restart,system/test_snmp.py,V3,
