2024-01-08 01:51:21,679 T0002: INFO  Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2024-01-08 01:51:21,680 T0002: INFO  TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2024-01-08 01:51:26,991 T0002: DEBUG Connected ...
2024-01-08 01:51:27,815 T0002: INFO  Prompt at the connection start: 'admin@V3:~$' 
2024-01-08 01:51:28,225 T0002: INFO  FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-08 01:51:28,484 T0002: INFO   01:51:28 up 31 days,  2:57,  1 user,  load average: 16.99, 28.49, 17.75
2024-01-08 01:51:28,484 T0002: INFO  admin@V3:~$ 
2024-01-08 01:51:28,899 T0002: INFO  FCMD: cat /proc/uptime
2024-01-08 01:51:29,156 T0002: INFO  2689059.05 211901929.30
2024-01-08 01:51:29,156 T0002: INFO  admin@V3:~$ 
2024-01-08 01:51:29,159 T0002: INFO  UPTIME: 2689059.05
2024-01-08 01:51:29,567 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:30,179 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:51:30,180 T0002: INFO  admin@V3:~$ 
2024-01-08 01:51:30,183 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:30,185 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:35,598 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:36,260 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:51:36,260 T0002: INFO  admin@V3:~$ 
2024-01-08 01:51:36,261 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:36,263 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:41,676 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:42,288 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:51:42,288 T0002: INFO  admin@V3:~$ 
2024-01-08 01:51:42,291 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:42,293 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:47,706 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:48,318 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:51:48,318 T0002: INFO  admin@V3:~$ 
2024-01-08 01:51:48,321 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:48,323 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:53,734 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:54,344 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:51:54,345 T0002: INFO  admin@V3:~$ 
2024-01-08 01:51:54,348 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:54,352 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:59,766 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:00,377 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:00,377 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:00,380 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:00,382 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:05,796 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:06,406 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:06,406 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:06,409 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:06,411 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:11,822 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:12,433 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:12,433 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:12,436 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:12,438 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:17,851 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:18,462 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:18,462 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:18,465 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:18,466 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:23,880 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:24,494 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:24,494 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:24,500 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:24,503 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:29,915 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:30,524 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:30,525 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:30,527 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:30,529 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:35,942 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:36,553 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:36,554 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:36,556 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:36,559 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:41,970 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:42,633 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:42,633 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:42,636 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:42,638 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:48,051 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:48,663 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:48,663 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:48,665 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:48,666 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:54,076 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:54,686 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:52:54,686 T0002: INFO  admin@V3:~$ 
2024-01-08 01:52:54,689 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:54,691 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:00,100 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:00,762 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:53:00,762 T0002: INFO  admin@V3:~$ 
2024-01-08 01:53:00,765 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:00,768 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:06,175 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:07,039 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:53:07,039 T0002: INFO  admin@V3:~$ 
2024-01-08 01:53:07,041 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:07,042 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:12,454 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:13,114 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:53:13,114 T0002: INFO  admin@V3:~$ 
2024-01-08 01:53:13,116 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:13,118 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:18,531 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:19,244 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:53:19,245 T0002: INFO  admin@V3:~$ 
2024-01-08 01:53:19,248 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:19,250 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:24,661 T0002: INFO  FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:25,373 T0002: INFO  Error response from daemon: No such container: bgp
2024-01-08 01:53:25,374 T0002: INFO  admin@V3:~$ 
2024-01-08 01:53:25,375 T0002: WARN  Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:25,377 T0002: WARN  Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:29,051 T0002: ERROR Failed to read hostname from vtysh - assuming sonic
2024-01-08 01:53:29,053 T0002: INFO  Base Prompt: sonic
2024-01-08 01:53:29,054 T0002: DEBUG Wait for system ready Ref: 866
2024-01-08 01:53:29,460 T0002: INFO  FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-08 01:53:29,717 T0002: INFO  4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2024-01-08 01:53:29,717 T0002: INFO  admin@V3:~$ 
2024-01-08 01:53:29,722 T0002: WARN  Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-08 01:53:29,724 T0002: INFO  SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:53:33,554 T0002: WARN  Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:53:33,555 T0002: INFO  
2024-01-08 01:53:33,555 T0002: INFO  Remote CMD: 'show platform summary'
2024-01-08 01:53:33,556 T0002: INFO  Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:53:33,556 T0002: INFO    File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:53:33,556 T0002: INFO      from show.main import cli
2024-01-08 01:53:33,556 T0002: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:53:33,556 T0002: INFO      if is_gearbox_configured():
2024-01-08 01:53:33,556 T0002: INFO         ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,556 T0002: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:53:33,556 T0002: INFO      app_db.connect(app_db.APPL_DB)
2024-01-08 01:53:33,556 T0002: INFO    File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:53:33,556 T0002: INFO      return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:53:33,556 T0002: INFO             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,556 T0002: INFO  RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:53:33,556 T0002: INFO  
2024-01-08 01:53:33,557 T0002: INFO  Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-08 01:53:33,557 T0002: INFO  Remote CMD: 'sudo show interfaces status '
2024-01-08 01:53:33,557 T0002: INFO  Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:53:33,557 T0002: INFO    File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:53:33,557 T0002: INFO      from show.main import cli
2024-01-08 01:53:33,557 T0002: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:53:33,557 T0002: INFO      if is_gearbox_configured():
2024-01-08 01:53:33,557 T0002: INFO         ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,557 T0002: INFO    File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:53:33,557 T0002: INFO      app_db.connect(app_db.APPL_DB)
2024-01-08 01:53:33,557 T0002: INFO    File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:53:33,557 T0002: INFO      return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:53:33,558 T0002: INFO             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,558 T0002: INFO  RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:53:33,558 T0002: INFO  
2024-01-08 01:53:33,558 T0002: INFO  admin@V3:~$ 
2024-01-08 01:53:33,558 T0002: ERROR Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:53:33,559 T0002: ERROR Failed to connect to device
