2024-01-08 01:51:20,261 T0000: NOTICE WORKER = gw4
2024-01-08 01:51:20,261 T0000: NOTICE using testbed file /data/work/logs/docker-master-449712-l2/testbed_1_1_1.yaml
2024-01-08 01:51:20,261 T0000: NOTICE Execution Start Time: 2024-01-08 01:51:20.260014
2024-01-08 01:51:20,261 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-449712-l2/gw4
2024-01-08 01:51:20,771 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2024-01-08 01:51:20,771 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 56.7%
2024-01-08 01:51:20,771 T0000: NOTICE ROOT_PATH: /repo
2024-01-08 01:51:20,771 T0000: NOTICE Python: 3.8.10
2024-01-08 01:51:20,771 T0000: NOTICE Topology unknown: D1T1:4
2024-01-08 01:51:20,771 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv test_ft_add_unknownvlan_interface,test_ft_lldp_ConfigManAddrEntry,test_ft_lldp_LocManAddrEntry,test_ft_lldp_LocManAddrLen,test_ft_lldp_LocManAddrlfld,test_ft_lldp_docker_restart,test_ft_lldp_lldplocportid,test_ft_lldp_lldplocsysdesc,test_ft_lldp_lldplocsysname,test_ft_lldp_non_default_config,test_ft_lldp_rem_man_addr_table,test_ft_lldp_with_remote_server,test_ft_net_snmp_agent_mib,test_ft_net_snmp_vacm_mib,test_ft_ntp_disable_enable_with_message_log,test_ft_port_fn_verify_shut_noshut,test_ft_portchannel_with_vlan_variations,test_ft_snmp_coldstart_trap,test_ft_snmp_docker_restart,test_ft_snmp_dot1q_dot1db_mib,test_ft_snmp_dot1q_tp_fdb_address,test_ft_snmp_dot1q_tp_fdb_port,test_ft_snmp_dot3_stats_table,test_ft_snmp_ent_physical_table,test_ft_snmp_entity_mib_all,test_ft_snmp_framework_mib,test_ft_snmp_host_resource_mib,test_ft_snmp_icmp_Msgs,test_ft_snmp_if_mib_all,test_ft_snmp_ifx_table,test_ft_snmp_ipAddressRowStatus_ipv6,test_ft_snmp_ipAddressStorageType_ipv6,test_ft_snmp_ip_Address_Table,test_ft_snmp_ip_IfStats_Table,test_ft_snmp_ip_NetToPhysical_Table,test_ft_snmp_ip_System_Stats_Table,test_ft_snmp_ip_forward_table,test_ft_snmp_ipv6_If_Forward_default_HopLimit,test_ft_snmp_ipv6scope_index_table,test_ft_snmp_mib_2,test_ft_snmp_mpd_mib,test_ft_snmp_notification_mib,test_ft_snmp_root_node_walk,test_ft_snmp_snmpv2_mib,test_ft_snmp_sysDescr,test_ft_snmp_sysName,test_ft_snmp_target_mib,test_ft_snmp_tcp_mib,test_ft_snmp_test_syUpTime,test_ft_snmp_ucd_diskio_mib,test_ft_snmp_ucd_la_table,test_ft_snmp_ucd_system_stats,test_ft_snmp_udp_mib,test_ft_snmp_user_based_sm_mib,test_ft_snmp_view_based_acm_mib,test_ft_ssh_add_user_verify,test_ft_ssh_service_disable,test_ft_tacacs_ssh_login_with_tacacs_operations,test_ft_verify_logs_at_the_time_of_ssh_login_success,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,test_ft_vlan_delete_with_member,test_ft_vlan_save_config_warm_and_fast_reboot,test_ft_vlan_trunk_tagged,test_ft_watermark_telemetry_interval,test_lldp_verify_counters,test_ntp_exists_config,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2024-01-08 01:51:20,771 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2024-01-08-01-48-49 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l2 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-449712-l2 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-449712-l2/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L2-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-449712-l2 --noop --feature-group master
2024-01-08 01:51:21,445 T0000: DEBUG 'errors' not set in properties for V3 assuming 'default'
2024-01-08 01:51:21,445 T0000: INFO  TGEN-IP 127.0.0.1
2024-01-08 01:51:21,446 T0000: WARN  Registering Topology
2024-01-08 01:51:21,461 T0000: INFO  Connecting all devices
2024-01-08 01:51:21,465 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/9', '1/10', '1/11', '1/12'] skip: False
2024-01-08 01:51:21,680 T0002: INFO  [D1-V3] Connecting to device (V3): sonic_ssh: 172.18.0.4:22 ..
2024-01-08 01:51:21,680 T0002: INFO  [D1-V3] TRY Authentication: 172.18.0.4:22 admin YourPaSsWoRd
2024-01-08 01:51:22,507 T0000: INFO  TG Scapy Init
2024-01-08 01:51:22,508 T0000: INFO  TG Base Init skip: False
2024-01-08 01:51:22,518 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2024-01-08 01:51:22,666 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2024_01_08_01_51_22_544238/gw4/default.log
2024-01-08 01:51:22,676 T0000: DEBUG REQ: tg_connect(port_list=['1/9', '1/10', '1/11', '1/12'])
2024-01-08 01:51:26,991 T0002: DEBUG [D1-V3] Connected ...
2024-01-08 01:51:27,815 T0002: INFO  [D1-V3] Prompt at the connection start: 'admin@V3:~$' 
2024-01-08 01:51:27,817 T0002: AUDIT [D1-V3] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2024-01-08 01:51:28,226 T0002: INFO  [D1-V3] FCMD: export TMOUT=0;stty cols 5000;uptime
2024-01-08 01:51:28,484 T0002: INFO  [D1-V3]  01:51:28 up 31 days,  2:57,  1 user,  load average: 16.99, 28.49, 17.75
2024-01-08 01:51:28,484 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:51:28,495 T0002: AUDIT [D1-V3] cat /proc/uptime
2024-01-08 01:51:28,899 T0002: INFO  [D1-V3] FCMD: cat /proc/uptime
2024-01-08 01:51:29,096 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/9": "port-9", "1/10": "port-10", "1/11": "port-11", "1/12": "port-12"}, "status": 1}
2024-01-08 01:51:29,107 T0000: INFO  TG Connection: Success
2024-01-08 01:51:29,107 T0000: INFO  TG Connect...done
2024-01-08 01:51:29,156 T0002: INFO  [D1-V3] 2689059.05 211901929.30
2024-01-08 01:51:29,157 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:51:29,159 T0002: INFO  [D1-V3] UPTIME: 2689059.05
2024-01-08 01:51:29,159 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:29,567 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:30,180 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:51:30,180 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:51:30,183 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:30,185 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:30,185 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:35,190 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:35,598 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:36,260 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:51:36,260 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:51:36,261 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:36,263 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:36,263 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:41,269 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:41,676 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:42,288 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:51:42,289 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:51:42,291 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:42,293 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:42,293 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:47,298 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:47,706 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:48,318 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:51:48,319 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:51:48,321 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:48,323 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:48,324 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:53,326 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:53,734 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:54,345 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:51:54,345 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:51:54,348 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:54,352 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:51:54,352 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:51:59,358 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:51:59,766 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:00,377 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:00,377 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:00,380 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:00,382 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:00,382 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:05,388 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:05,797 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:06,406 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:06,407 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:06,409 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:06,411 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:06,412 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:11,414 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:11,822 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:12,433 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:12,433 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:12,436 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:12,438 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:12,438 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:17,444 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:17,851 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:18,462 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:18,463 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:18,465 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:18,466 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:18,466 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:23,472 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:23,880 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:24,494 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:24,495 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:24,500 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:24,503 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:24,504 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:29,510 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:29,915 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:30,524 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:30,525 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:30,527 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:30,529 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:30,529 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:35,535 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:35,942 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:36,554 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:36,554 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:36,557 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:36,559 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:36,559 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:41,562 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:41,970 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:42,633 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:42,633 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:42,636 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:42,638 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:42,638 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:47,644 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:48,052 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:48,663 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:48,663 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:48,665 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:48,666 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:48,666 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:53,670 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:54,076 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:54,686 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:52:54,686 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:52:54,689 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:52:54,691 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:52:54,691 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:52:59,693 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:00,101 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:00,762 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:53:00,762 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:53:00,765 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:00,768 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:00,768 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:53:05,770 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:06,175 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:07,039 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:53:07,039 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:53:07,042 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:07,042 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:07,042 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:53:12,046 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:12,454 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:13,114 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:53:13,114 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:53:13,116 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:13,118 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:13,118 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:53:18,122 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:18,532 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:19,245 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:53:19,245 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:53:19,248 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:19,250 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:19,250 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:53:24,254 T0002: AUDIT [D1-V3] sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:24,662 T0002: INFO  [D1-V3] FCMD: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:25,373 T0002: INFO  [D1-V3] Error response from daemon: No such container: bgp
2024-01-08 01:53:25,374 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:53:25,375 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2024-01-08 01:53:25,377 T0002: WARN  [D1-V3] Failed to read hostname from vtysh retry again in 5 sec
2024-01-08 01:53:25,377 T0002: INFO  Sleep for 5 sec(s)... @371
2024-01-08 01:53:29,051 T0002: ERROR [D1-V3] Failed to read hostname from vtysh - assuming sonic
2024-01-08 01:53:29,053 T0002: INFO  [D1-V3] Base Prompt: sonic
2024-01-08 01:53:29,054 T0002: DEBUG [D1-V3] Wait for system ready Ref: 866
2024-01-08 01:53:29,460 T0002: INFO  [D1-V3] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2024-01-08 01:53:29,717 T0002: INFO  [D1-V3] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2024-01-08 01:53:29,718 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:53:29,722 T0002: WARN  [D1-V3] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2024-01-08 01:53:29,724 T0002: INFO  [D1-V3] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:53:33,554 T0002: WARN  [D1-V3] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:53:33,555 T0002: INFO  [D1-V3] 
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3] Remote CMD: 'show platform summary'
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]     from show.main import cli
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]     if is_gearbox_configured():
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,556 T0002: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3] 
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3] Remote CMD: 'sudo show interfaces status '
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]   File "/usr/local/bin/show", line 5, in <module>
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]     from show.main import cli
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]     if is_gearbox_configured():
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]        ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]     app_db.connect(app_db.APPL_DB)
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2024-01-08 01:53:33,557 T0002: INFO  [D1-V3]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2024-01-08 01:53:33,558 T0002: INFO  [D1-V3]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-08 01:53:33,558 T0002: INFO  [D1-V3] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2024-01-08 01:53:33,558 T0002: INFO  [D1-V3] 
2024-01-08 01:53:33,558 T0002: INFO  [D1-V3] admin@V3:~$ 
2024-01-08 01:53:33,558 T0002: ERROR [D1-V3] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2024-01-08 01:53:33,559 T0002: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2024-01-08 01:53:33,559 T0002: ERROR [D1-V3] Failed to connect to device
2024-01-08 01:53:33,560 T0000: ERROR Failed to connect (['V3'])
2024-01-08 01:53:33,560 T0000: INFO  --FINISH--RUN--4 @559
