ordering items took 0:00:01
Tests considered 72 and ignored 317
2023-12-28 00:59:12,548 T0000: NOTICE WORKER = gw7
2023-12-28 00:59:12,548 T0000: NOTICE using testbed file /data/work/logs/docker-master-442372-l3/testbed_1_1_4.yaml
2023-12-28 00:59:12,548 T0000: NOTICE Execution Start Time: 2023-12-28 00:59:12.546650
2023-12-28 00:59:12,548 T0000: NOTICE LOGS PATH: /data/work/logs/docker-master-442372-l3/gw7
2023-12-28 00:59:13,076 T0000: NOTICE VERSION: UNKNOWN UNKNOWN UNKNOWN
2023-12-28 00:59:13,076 T0000: NOTICE HOST: sonicmgmtmaster MEM: 376gb 38.2%
2023-12-28 00:59:13,076 T0000: NOTICE ROOT_PATH: /repo
2023-12-28 00:59:13,077 T0000: NOTICE Python: 3.8.10
2023-12-28 00:59:13,077 T0000: NOTICE Topology unknown: D1T1:4
2023-12-28 00:59:13,077 T0000: DEBUG 
SUITE ARGS: --load-image none --max-time module 9000 --max-time function 5400 --max-time session 3600 --logs-level=debug --topology-check=function --env SPYTEST_TESTBED_IGNORE_CONSTRAINTS TG,TGCARD,TGSPEED,CHIP,MODEL --noop --env SPYTEST_RESET_CONSOLES 0 --noop --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 1 --noop --env SPYTEST_RECOVERY_CR_PER_CMD_POST_OP 1 --noop --env SPYTEST_BATCH_POLL_STATUS_TIME 300 --noop --env SPYTEST_BATCH_DEAD_NODE_MAX_TIME 7200 --noop --breakout-mode none --env SPYTEST_SHUTDOWN_FREE_PORTS 1 --env SPYTEST_HOOKS_BREAKOUT_UITYPE click --env SPYTEST_ONREBOOT_RENEW_MGMT_IP 0 --env SPYTEST_VERIFY_CSV_MIN_TOPOLOGY 1 --env SPYTEST_CMD_FAIL_RESULT_SUPPORT 0 --env SPYTEST_ROUTING_CONFIG_MODE split --env SPYTEST_CLEAR_DEVICE_METADATA_BGP_ASN 1 --env SPYTEST_TEXTFSM_USE_BUNDLED_PARSER 1 --feature-group master --ifname-type native --feature-disable bcmcmd --feature-disable warm-reboot --save config-db module --tclist-csv TestBGPConfed.test_confed_route_distribution_with_rmap,TestBGPConfed.test_ipv6_confed_route_distribution,TestBGPConfed.test_ipv6_confed_with_rr,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_authentication,TestBGPIPvxRouteAdvertisementFilter.test_bgp_ebgp4_nbr_update_source,TestBGPIPvxRouteAdvertisementFilter.test_bgp_route_map_with_community,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_distribute_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_filter_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_prefix_list_out_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_aggregate_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_route_map_in_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_static_blackhole_rt_redistribute_with_routemap_ipv6,TestBGPL3Lag.test_ft_bgp_l3lag_peer_traffic_check,TestBGPRif.test_bgp_route_aggregation_4byteASN,TestBGPRif.test_ft_bgp_clear,TestBGPRif.test_ft_bgp_graceful_restart_and_aware_routers,TestBGPRif.test_ft_bgp_peer_traffic_check,TestBGPRif.test_ft_bgp_rmap,TestBGPRif.test_ft_bgp_v4_dyn_nbr,TestBGPRif.test_ft_bgp_v6_dyn_nbr,TestBGPRif.test_ft_bgp_v6_link_local_bgp,TestBGPRrTraffic.test_ft_bgp6_rr_traffic_check,TestBGPVeLag.test_ft_bgp_clear,TestBGPVeLag.test_ft_bgp_peer_traffic_check,test_VrfFun001_06,test_VrfFun_05_50,test_VrfFun_10_12_14,test_VrfFun_20_24_25_32_33_44_45,test_VrfFun_26_27,test_cli_validation_bgp_router_config,test_cli_validation_ip_address,test_ft_arp_dynamic_renew_traffic_test,test_ft_bgp_ebgp_community_map,test_ft_bgp_ibgp_RR_Loop,test_ft_ip6_static_route_traffic_forward_blackhole,test_ft_ip_static_ip_on_mgmt_intrf,test_ft_ip_static_route_traffic_forward,test_ft_ip_v4_v6_L2_L3_translation,test_ft_ipv6_neighbor_entry,test_ft_l3_performance_enhancements_v4_route_intstall_withdraw,test_ft_nat_docker_restart,test_ft_ping_v4_v6_after_ip_change_pc,test_ft_ping_v4_v6_vlan,test_ft_qos_config_mgmt_verifying_config_with_save_reboot,test_ft_sflow_max_sflow_collector_config,test_ft_sflow_sampling_v6_sFlow_collector,test_ft_system_config_mgmt_verifying_config_with_save_reboot_sflow,test_ft_verify_interfaces_order,test_l2_to_l3_port,test_l3_v4_route_po_1,test_vrf_bgp,test_vrf_reload,test_vrf_route_leak,test_vrf_scale,TestBGPRif.test_ft_bgp_ipv4_no_route_aggregation_for_exact_prefix_match,TestBGPRif.test_ft_bgp_ipv4_route_aggregation_atomic_aggregate_without_as_set,TestBGPRif.test_ft_bgp_ipv6_route_aggregation_with_as_set,TestBGPRif.test_ft_bgp_v4_max_dyn_nbr,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv4,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_connected_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_redistribute_static_ipv6,TestBGPIPvxRouteAdvertisementFilter.test_default_originate_ipv6,test_spytest_infra_first,test_spytest_infra_second,test_spytest_infra_last --noop

2023-12-28 00:59:13,077 T0000: NOTICE ARGS: --logs-level debug --results-prefix=results --get-tech-support none --fetch-core-files none --syslog-check none --save config-db module --topology-check module --logs-path logs/2023-12-28-00-54-25 --continue-on-collection-errors --max-time session 0 --max-time module 0 --max-time function 0 --noop --tryssh=0 --testbed-file testbed.yaml --env SPYTEST_RPS_DEBUG 0 --tclist-bucket 1,2,4 --test-suite community-vs-l3 --email rama.kristipati@broadcom.com --env SPYTEST_SCAPY_DBG_LVL 2 --noop --env SPYTEST_EMAIL_FROM SPyTest-VSNet@broadcom.com --noop --logs-path logs/docker-master-442372-l3 --env SPYTEST_EMAIL_BODY_PREFIX http://10.193.81.56:8080/sonic_mgmt_master/work/logs/docker-master-442372-l3/dashboard.html --email-subject-nargs VSNet-sonic_mgmt_master-DOCKER-L3-{{bldver}} : {{passrate}}: {{pass_cnt}}/{{executed}} docker-master-442372-l3 --noop --feature-group master
2023-12-28 00:59:13,739 T0000: DEBUG 'errors' not set in properties for V2 assuming 'default'
2023-12-28 00:59:13,739 T0000: INFO  TGEN-IP 127.0.0.1
2023-12-28 00:59:13,740 T0000: WARN  Registering Topology
2023-12-28 00:59:13,755 T0000: INFO  Connecting all devices
2023-12-28 00:59:13,759 T0000: INFO  Loading scapy:1.0 127.0.0.1 Ports: ['1/5', '1/6', '1/7', '1/8'] skip: False
2023-12-28 00:59:13,987 T0002: INFO  [D1-V2] Connecting to device (V2): sonic_ssh: 172.18.0.3:22 ..
2023-12-28 00:59:13,988 T0002: INFO  [D1-V2] TRY Authentication: 172.18.0.3:22 admin YourPaSsWoRd
2023-12-28 00:59:14,771 T0000: INFO  TG Scapy Init
2023-12-28 00:59:14,771 T0000: INFO  TG Base Init skip: False
2023-12-28 00:59:14,781 T0000: INFO  TG Scapy Connect 127.0.0.1:8009
2023-12-28 00:59:14,886 T0000: INFO  Server Logs Path /data/work/scapy-tgen/logs/current/inst-2023_12_28_00_59_14_807718/gw7/default.log
2023-12-28 00:59:14,897 T0000: DEBUG REQ: tg_connect(port_list=['1/5', '1/6', '1/7', '1/8'])
2023-12-28 00:59:19,389 T0002: DEBUG [D1-V2] Connected ...
2023-12-28 00:59:20,212 T0002: INFO  [D1-V2] Prompt at the connection start: 'admin@V2:~$' 
2023-12-28 00:59:20,215 T0002: AUDIT [D1-V2] ['export TMOUT=0', 'stty cols 5000', 'uptime']
2023-12-28 00:59:20,623 T0002: INFO  [D1-V2] FCMD: export TMOUT=0;stty cols 5000;uptime
2023-12-28 00:59:20,880 T0002: INFO  [D1-V2]  00:59:20 up 20 days,  2:01,  1 user,  load average: 15.55, 15.25, 11.69
2023-12-28 00:59:20,881 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:20,891 T0002: AUDIT [D1-V2] cat /proc/uptime
2023-12-28 00:59:21,297 T0002: INFO  [D1-V2] FCMD: cat /proc/uptime
2023-12-28 00:59:21,552 T0002: INFO  [D1-V2] 1735300.66 136853619.75
2023-12-28 00:59:21,552 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:21,554 T0002: INFO  [D1-V2] UPTIME: 1735300.66
2023-12-28 00:59:21,557 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:21,964 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:22,776 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 00:59:22,776 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:22,779 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:22,781 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 00:59:22,781 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 00:59:22,855 T0000: DEBUG RESP: tg_connect {"port_handle": {"1/5": "port-5", "1/6": "port-6", "1/7": "port-7", "1/8": "port-8"}, "status": 1}
2023-12-28 00:59:22,865 T0000: INFO  TG Connection: Success
2023-12-28 00:59:22,865 T0000: INFO  TG Connect...done
2023-12-28 00:59:27,785 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:28,193 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:28,804 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 00:59:28,804 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:28,807 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:28,808 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 00:59:28,808 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 00:59:33,813 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:34,225 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:34,887 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 00:59:34,887 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:34,890 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:34,892 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 00:59:34,892 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 00:59:39,897 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:40,302 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:41,012 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 00:59:41,013 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:41,016 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:41,018 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 00:59:41,018 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 00:59:46,021 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:46,426 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:47,236 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 00:59:47,236 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:47,239 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:47,241 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 00:59:47,242 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 00:59:52,245 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:52,651 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:53,311 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 00:59:53,311 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:53,313 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:53,314 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 00:59:53,314 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 00:59:58,317 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:58,726 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:59,388 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 00:59:59,388 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 00:59:59,391 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 00:59:59,393 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 00:59:59,394 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:04,397 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:04,804 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:05,464 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:05,464 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:05,467 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:05,470 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:05,470 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:10,473 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:10,878 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:11,489 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:11,489 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:11,493 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:11,497 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:11,497 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:16,502 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:16,910 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:17,621 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:17,621 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:17,624 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:17,625 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:17,626 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:22,629 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:23,034 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:23,692 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:23,692 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:23,693 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:23,694 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:23,694 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:28,700 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:29,107 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:29,766 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:29,767 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:29,769 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:29,771 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:29,771 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:34,777 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:35,188 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:35,849 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:35,850 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:35,852 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:35,854 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:35,855 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:40,860 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:41,269 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:41,928 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:41,928 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:41,931 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:41,932 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:41,933 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:46,939 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:47,350 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:48,014 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:48,014 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:48,019 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:48,022 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:48,022 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:53,025 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:53,431 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:54,243 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:00:54,244 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:00:54,246 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:54,249 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:00:54,249 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:00:59,253 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:00:59,661 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:00,321 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:01:00,321 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:01:00,323 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:00,324 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:01:00,324 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:01:05,329 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:05,741 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:06,451 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:01:06,451 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:01:06,454 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:06,456 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:01:06,456 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:01:11,461 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:11,869 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:12,531 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:01:12,531 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:01:12,534 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:12,535 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:01:12,535 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:01:17,541 T0002: AUDIT [D1-V2] sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:17,948 T0002: INFO  [D1-V2] FCMD: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:18,607 T0002: INFO  [D1-V2] Error response from daemon: No such container: bgp
2023-12-28 01:01:18,608 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:01:18,609 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_no_response_from_container command: sudo vtysh -c 'show running-config | include hostname'
2023-12-28 01:01:18,611 T0002: WARN  [D1-V2] Failed to read hostname from vtysh retry again in 5 sec
2023-12-28 01:01:18,611 T0002: INFO  Sleep for 5 sec(s)... @371
2023-12-28 01:01:23,613 T0002: ERROR [D1-V2] Failed to read hostname from vtysh - assuming sonic
2023-12-28 01:01:23,614 T0002: INFO  [D1-V2] Base Prompt: sonic
2023-12-28 01:01:23,615 T0002: DEBUG [D1-V2] Wait for system ready Ref: 866
2023-12-28 01:01:24,020 T0002: INFO  [D1-V2] FCMD: sudo md5sum /etc/spytest/remote/spytest-helper.py
2023-12-28 01:01:24,277 T0002: INFO  [D1-V2] 4522abaafb8e29890a8377a810228525  /etc/spytest/remote/spytest-helper.py
2023-12-28 01:01:24,277 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:01:24,280 T0002: WARN  [D1-V2] Execute 'sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300' with timeout 600 sec -- TRY 1
2023-12-28 01:01:24,281 T0002: INFO  [D1-V2] SCMD: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:01:28,104 T0002: WARN  [D1-V2] Skipped error checking in session init but detected pattern: containing_python_traceback command: sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:01:28,105 T0002: INFO  [D1-V2] 
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2] Remote CMD: 'show platform summary'
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2] Error: Failed to execute 'show platform summary' (out: '') (err: 'Traceback (most recent call last):
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2]     from show.main import cli
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2]     if is_gearbox_configured():
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:01:28,106 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2]     app_db.connect(app_db.APPL_DB)
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2] 
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2] Remote CMD: 'cat /usr/share/sonic/device/None/None/port_config.ini | tail -1'
2023-12-28 01:01:28,107 T0002: INFO  [D1-V2] Remote CMD: 'sudo show interfaces status '
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2] Error: Failed to execute 'sudo show interfaces status ' (out: '') (err: 'Traceback (most recent call last):
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2]   File "/usr/local/bin/show", line 5, in <module>
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2]     from show.main import cli
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 307, in <module>
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2]     if is_gearbox_configured():
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2]        ^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2]   File "/usr/local/lib/python3.11/dist-packages/show/main.py", line 248, in is_gearbox_configured
2023-12-28 01:01:28,108 T0002: INFO  [D1-V2]     app_db.connect(app_db.APPL_DB)
2023-12-28 01:01:28,109 T0002: INFO  [D1-V2]   File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1821, in connect
2023-12-28 01:01:28,109 T0002: INFO  [D1-V2]     return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
2023-12-28 01:01:28,109 T0002: INFO  [D1-V2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-28 01:01:28,109 T0002: INFO  [D1-V2] RuntimeError: Unable to connect to redis: Cannot assign requested address')
2023-12-28 01:01:28,109 T0002: INFO  [D1-V2] 
2023-12-28 01:01:28,109 T0002: INFO  [D1-V2] admin@V2:~$ 
2023-12-28 01:01:28,110 T0002: ERROR [D1-V2] Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  
2023-12-28 01:01:28,110 T0002: ERROR exception in thread: Traceback (most recent call last):
  File "/repo/utilities/parallel.py", line 159, in _thread_func
    retvals[index] = func(*args, **kwargs)
  File "/repo/spytest/net.py", line 1064, in connect_to_device
    show_ver_output = self.connect_to_device_real(access, retry, recon, recover)
  File "/repo/spytest/net.py", line 1290, in connect_to_device_real
    self.do_common_init(devname, phase=0, max_ready_wait=max_ready_wait)
  File "/repo/spytest/net.py", line 866, in do_common_init
    sys_status = self.wa.wait_system_status(devname, max_time=max_ready_wait)
  File "/repo/spytest/framework.py", line 1616, in wait_system_status
    return self._wait_for_ports(dut, max_time)
  File "/repo/spytest/framework.py", line 1605, in _wait_for_ports
    return self.net.apply_remote(dut, "wait-for-ports", [max_time])
  File "/repo/spytest/net.py", line 4523, in apply_remote
    raise ValueError(msg)
ValueError: Failed to execute the command sudo python /etc/spytest/remote/spytest-helper.py --wait-for-ports 300  

2023-12-28 01:01:28,110 T0002: ERROR [D1-V2] Failed to connect to device
2023-12-28 01:01:28,111 T0000: ERROR Failed to connect (['V2'])
2023-12-28 01:01:28,111 T0000: INFO  --FINISH--RUN--4 @559
