#,Feature,TestCase,Result,ResultType,ExecutedOn,Description,Function,Module,Devices,KnownIssue
1,Regression,FtOpSoSwLagFn042,Fail,Mapped,2024-01-06 02:55:56,"Portchannel PortChannel7 on V1 with member ['Ethernet16', 'Ethernet20'] verification failed",test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
2,Regression,FtOpSoSwLagFn041,Fail,Mapped,2024-01-06 02:55:56,"Portchannel PortChannel7 on V1 with member ['Ethernet16', 'Ethernet20'] verification failed",test_ft_portchannel_with_vlan_variations,switching/test_portchannel.py,"V1, V2",
3,PortChannel Config Enhancements,FtOpSoSwPominFn007,ConfigFail,Mapped,2024-01-06 02:56:35,pre-test configuration failed Invalid error code PortChannel Verification Failed : unknown message identifier 'PortChannel Verification Failed' @5430,test_ft_verify_min_links_functionality_by_flapping_all_member_ports_007,switching/test_portchannel.py,"V1, V2",
4,Regression,FtOpSoSyInIpFn002,DUTFail,Mapped,2024-01-06 03:01:16,config command 'sudo -s config interface ip remove Ethernet16 11.11.11.11/24' failed,test_ft_port_fn_verify_shut_noshut,system/test_interface.py,"V1, V2",
5,Regression,ft_ssh_service_disable,Pass,Mapped,2024-01-06 03:06:52,Test case passed,test_ft_ssh_service_disable,system/test_ssh.py,"V1, V2",
6,Regression,ft_ssh_add_user_verify,Fail,Mapped,2024-01-06 03:15:57,Test case Failed.,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
7,Control Plane ACL,test_ft_controlplane_acl_service_sshv4,Pass,SubTest,2024-01-06 03:15:57,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
8,Control Plane ACL,test_ft_controlplane_acl_service_sshv6,Pass,SubTest,2024-01-06 03:15:57,SSH failed,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
9,Control Plane ACL,test_ft_controlplane_acl_service_snmp,Fail,SubTest,2024-01-06 03:15:57,SNMP output is not found after walk of with control plane ACL service SNMP after reboot OID,test_ft_ssh_add_user_verify,system/test_ssh.py,"V1, V2",
10,Regression,CETA_SONIC_67575,Pass,Mapped,2024-01-06 03:16:18,Test case passed,test_ft_verify_logs_at_the_time_of_ssh_login_success,system/test_ssh.py,"V1, V2",
